#!/bin/sh

function usage()
{
    $JAVA_HOME/bin/java -jar $VMBK_JAR/vmbkcmd.jar help
    echo
    echo "Debug Mode:"
    echo "$0  -d=<port> | --debug=<port>  <command> <options....>"
    echo ""
}

export VMBK_HOME=VMBK_DIR
export JAVA_HOME=$VMBK_HOME/jre
export VMBK_JAR=$VMBK_HOME/jar
export VMBK_LIB=$VMBK_HOME/lib/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VMBK_LIB/

export LIBRARY_PATH_OPTIONS="-Djava.library.path=$VMBK_LIB -classpath $VMBK_JAR"

export ORIG_DIR=$PWD
cd $VMBK_HOME
#if one parameter and start with ./ 
if [[ $# -eq 1 && $1 == "./"* ]]; then
        param=$1
        param="${param/.\//$ORIG_DIR/}"
        echo Changed file relative path $1 to $param
        set -- $param
fi

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | help)
            usage
            exit
            ;;
        -d | --debug)
            PORT=$VALUE
            export DEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,address=$PORT,server=y"
            ;;
        *)
            $JAVA_HOME/bin/java $DEBUG -ea -server -Xms10G -Xmx10G -server -XX:NewSize=2G $LIBRARY_PATH_OPTIONS -jar $VMBK_JAR/vmbkcmd.jar $@
            cd $ORIG_DIR
            exit $?
            ;;
    esac
    shift
done

$JAVA_HOME/bin/java $DEBUG -ea -server -Xms10G -Xmx10G -server -XX:NewSize=2G  $LIBRARY_PATH_OPTIONS -jar $VMBK_JAR/vmbkcmd.jar $@
cd $ORIG_DIR
exit $?