/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __com_vmware_jvix_jDiskLibImpl__
#define __com_vmware_jvix_jDiskLibImpl__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_InitJNI (JNIEnv *env, jobject, jint, jint, jobject, jstring);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_InitExJNI (JNIEnv *env, jobject, jint, jint, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_com_vmware_jvix_jDiskLibImpl_ExitJNI (JNIEnv *env, jobject);
JNIEXPORT jstring JNICALL Java_com_vmware_jvix_jDiskLibImpl_ListTransportModesJNI (JNIEnv *env, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_CleanupJNI (JNIEnv *env, jobject, jobject, jintArray, jintArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_ConnectJNI (JNIEnv *env, jobject, jobject, jlongArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_ConnectExJNI (JNIEnv *env, jobject, jobject, jboolean, jstring, jstring, jlongArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_DisconnectJNI (JNIEnv *env, jobject, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_CreateJNI (JNIEnv *env, jobject, jlong, jstring, jobject, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_CreateChildJNI (JNIEnv *env, jobject, jlong, jstring, jint, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_OpenJNI (JNIEnv *env, jobject, jlong, jstring, jint, jlongArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_QueryAllocatedBlocksJNI (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_GetInfoJNI (JNIEnv *env, jobject, jlong, jobject);
JNIEXPORT jstring JNICALL Java_com_vmware_jvix_jDiskLibImpl_GetTransportModeJNI (JNIEnv *env, jobject, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_CloseJNI (JNIEnv *env, jobject, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_ReadJNI (JNIEnv *env, jobject, jlong, jlong, jlong, jbyteArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_ReadAsyncJNI (JNIEnv *env, jobject, jlong, jlong, jobject, jint, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_WriteJNI (JNIEnv *env, jobject, jlong, jlong, jlong, jbyteArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_WriteAsyncJNI (JNIEnv *env, jobject, jlong, jlong, jobject, jint, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_WaitJNI (JNIEnv *env, jobject, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_FlushJNI (JNIEnv *env, jobject, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_ReadMetadataJNI (JNIEnv *env, jobject, jlong, jstring, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_WriteMetadataJNI (JNIEnv *env, jobject, jlong, jstring, jstring);
JNIEXPORT jobjectArray JNICALL Java_com_vmware_jvix_jDiskLibImpl_GetMetadataKeysJNI (JNIEnv *env, jobject, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_UnlinkJNI (JNIEnv *env, jobject, jlong, jstring);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_GrowJNI (JNIEnv *env, jobject, jlong, jstring, jlong, jboolean, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_ShrinkJNI (JNIEnv *env, jobject, jlong, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_DefragmentJNI (JNIEnv *env, jobject, jlong, jobject);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_RenameJNI (JNIEnv *env, jobject, jstring, jstring);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_CloneJNI (JNIEnv *env, jobject, jlong, jstring, jlong, jstring, jobject, jobject, jboolean);
JNIEXPORT jstring JNICALL Java_com_vmware_jvix_jDiskLibImpl_GetErrorTextJNI (JNIEnv *env, jobject, jlong, jstring);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_IsAttachPossibleJNI(
   JNIEnv *env, jobject, jlong, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_AttachJNI (JNIEnv *env, jobject, jlong, jlong);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_SpaceNeededForCloneJNI (JNIEnv *env, jobject, jlong, jint, jlongArray);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_CheckRepairJNI (JNIEnv *env, jobject, jlong, jstring, jboolean);
JNIEXPORT void JNICALL Java_com_vmware_jvix_jDiskLibImpl_PerturbEnableJNI (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_SetInjectedFaultJNI(JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT jlong JNICALL Java_com_vmware_jvix_jDiskLibImpl_GetConnectParamsJNI(JNIEnv *env, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __com_vmware_jvix_jDiskLibImpl__ */
