/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VMGuestAppMonitor */

#ifndef _Included_VMGuestAppMonitor
#define _Included_VMGuestAppMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VMGuestAppMonitor
 * Method:    enable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_VMGuestAppMonitor_enable
  (JNIEnv *, jobject);

/*
 * Class:     VMGuestAppMonitor
 * Method:    disable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_VMGuestAppMonitor_disable
  (JNIEnv *, jobject);

/*
 * Class:     VMGuestAppMonitor
 * Method:    isEnabled
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_VMGuestAppMonitor_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     VMGuestAppMonitor
 * Method:    markActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_VMGuestAppMonitor_markActive
  (JNIEnv *, jobject);

/*
 * Class:     VMGuestAppMonitor
 * Method:    getAppStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_VMGuestAppMonitor_getAppStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
