/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.BackupMode;
import com.vmware.safekeeping.cxf.rest.model.ResultActionBackup;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * AbstractResultActionBackupForEntityWithDisks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class AbstractResultActionBackupForEntityWithDisks extends ResultActionBackup  {
  @JsonProperty("NumberOfDisk")
  private Integer numberOfDisk = null;

  @JsonProperty("Cipher")
  private Boolean cipher = null;

  @JsonProperty("Compressed")
  private Boolean compressed = null;

  public AbstractResultActionBackupForEntityWithDisks numberOfDisk(Integer numberOfDisk) {
    this.numberOfDisk = numberOfDisk;
    return this;
  }

  /**
   * Get numberOfDisk
   * @return numberOfDisk
   **/
  @JsonProperty("NumberOfDisk")
  @Schema(description = "")
  public Integer getNumberOfDisk() {
    return numberOfDisk;
  }

  public void setNumberOfDisk(Integer numberOfDisk) {
    this.numberOfDisk = numberOfDisk;
  }

  public AbstractResultActionBackupForEntityWithDisks cipher(Boolean cipher) {
    this.cipher = cipher;
    return this;
  }

  /**
   * Get cipher
   * @return cipher
   **/
  @JsonProperty("Cipher")
  @Schema(description = "")
  public Boolean isCipher() {
    return cipher;
  }

  public void setCipher(Boolean cipher) {
    this.cipher = cipher;
  }

  public AbstractResultActionBackupForEntityWithDisks compressed(Boolean compressed) {
    this.compressed = compressed;
    return this;
  }

  /**
   * Get compressed
   * @return compressed
   **/
  @JsonProperty("Compressed")
  @Schema(description = "")
  public Boolean isCompressed() {
    return compressed;
  }

  public void setCompressed(Boolean compressed) {
    this.compressed = compressed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractResultActionBackupForEntityWithDisks abstractResultActionBackupForEntityWithDisks = (AbstractResultActionBackupForEntityWithDisks) o;
    return Objects.equals(this.numberOfDisk, abstractResultActionBackupForEntityWithDisks.numberOfDisk) &&
        Objects.equals(this.cipher, abstractResultActionBackupForEntityWithDisks.cipher) &&
        Objects.equals(this.compressed, abstractResultActionBackupForEntityWithDisks.compressed) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfDisk, cipher, compressed, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractResultActionBackupForEntityWithDisks {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    numberOfDisk: ").append(toIndentedString(numberOfDisk)).append("\n");
    sb.append("    cipher: ").append(toIndentedString(cipher)).append("\n");
    sb.append("    compressed: ").append(toIndentedString(compressed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
