/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AbstractResultActionWithSubOperations;
import com.vmware.safekeeping.cxf.rest.model.FcoLocation;
import com.vmware.safekeeping.cxf.rest.model.GenerationInfo;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * AbstractResultActionBackupRestore
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class AbstractResultActionBackupRestore extends AbstractResultActionWithSubOperations  {
  @JsonProperty("GenerationId")
  private Integer generationId = null;

  @JsonProperty("GenerationInfo")
  private GenerationInfo generationInfo = null;

  @JsonProperty("Index")
  private Integer index = null;

  @JsonProperty("Locations")
  private FcoLocation locations = null;

  @JsonProperty("Phase")
  private String phase = null;

  @JsonProperty("TargetName")
  private String targetName = null;

  @JsonProperty("Success")
  private Boolean success = null;

  public AbstractResultActionBackupRestore generationId(Integer generationId) {
    this.generationId = generationId;
    return this;
  }

  /**
   * Get generationId
   * @return generationId
   **/
  @JsonProperty("GenerationId")
  @Schema(description = "")
  public Integer getGenerationId() {
    return generationId;
  }

  public void setGenerationId(Integer generationId) {
    this.generationId = generationId;
  }

  public AbstractResultActionBackupRestore generationInfo(GenerationInfo generationInfo) {
    this.generationInfo = generationInfo;
    return this;
  }

  /**
   * Get generationInfo
   * @return generationInfo
   **/
  @JsonProperty("GenerationInfo")
  @Schema(description = "")
  @Valid
  public GenerationInfo getGenerationInfo() {
    return generationInfo;
  }

  public void setGenerationInfo(GenerationInfo generationInfo) {
    this.generationInfo = generationInfo;
  }

  public AbstractResultActionBackupRestore index(Integer index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   **/
  @JsonProperty("Index")
  @Schema(description = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public AbstractResultActionBackupRestore locations(FcoLocation locations) {
    this.locations = locations;
    return this;
  }

  /**
   * Get locations
   * @return locations
   **/
  @JsonProperty("Locations")
  @Schema(description = "")
  @Valid
  public FcoLocation getLocations() {
    return locations;
  }

  public void setLocations(FcoLocation locations) {
    this.locations = locations;
  }

  public AbstractResultActionBackupRestore phase(String phase) {
    this.phase = phase;
    return this;
  }

  /**
   * Get phase
   * @return phase
   **/
  @JsonProperty("Phase")
  @Schema(description = "")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  public AbstractResultActionBackupRestore targetName(String targetName) {
    this.targetName = targetName;
    return this;
  }

  /**
   * Get targetName
   * @return targetName
   **/
  @JsonProperty("TargetName")
  @Schema(description = "")
  public String getTargetName() {
    return targetName;
  }

  public void setTargetName(String targetName) {
    this.targetName = targetName;
  }

  public AbstractResultActionBackupRestore success(Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   **/
  @JsonProperty("Success")
  @Schema(description = "")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractResultActionBackupRestore abstractResultActionBackupRestore = (AbstractResultActionBackupRestore) o;
    return Objects.equals(this.generationId, abstractResultActionBackupRestore.generationId) &&
        Objects.equals(this.generationInfo, abstractResultActionBackupRestore.generationInfo) &&
        Objects.equals(this.index, abstractResultActionBackupRestore.index) &&
        Objects.equals(this.locations, abstractResultActionBackupRestore.locations) &&
        Objects.equals(this.phase, abstractResultActionBackupRestore.phase) &&
        Objects.equals(this.targetName, abstractResultActionBackupRestore.targetName) &&
        Objects.equals(this.success, abstractResultActionBackupRestore.success) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generationId, generationInfo, index, locations, phase, targetName, success, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractResultActionBackupRestore {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    generationId: ").append(toIndentedString(generationId)).append("\n");
    sb.append("    generationInfo: ").append(toIndentedString(generationInfo)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    targetName: ").append(toIndentedString(targetName)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
