/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AbstractResultActionVirtualBackup;
import com.vmware.safekeeping.cxf.rest.model.BackupMode;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * AbstractResultActionVirtualBackupForEntityWithDisks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class AbstractResultActionVirtualBackupForEntityWithDisks extends AbstractResultActionVirtualBackup  {
  @JsonProperty("NumberOfDisk")
  private Integer numberOfDisk = null;

  public AbstractResultActionVirtualBackupForEntityWithDisks numberOfDisk(Integer numberOfDisk) {
    this.numberOfDisk = numberOfDisk;
    return this;
  }

  /**
   * Get numberOfDisk
   * @return numberOfDisk
   **/
  @JsonProperty("NumberOfDisk")
  @Schema(description = "")
  public Integer getNumberOfDisk() {
    return numberOfDisk;
  }

  public void setNumberOfDisk(Integer numberOfDisk) {
    this.numberOfDisk = numberOfDisk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractResultActionVirtualBackupForEntityWithDisks abstractResultActionVirtualBackupForEntityWithDisks = (AbstractResultActionVirtualBackupForEntityWithDisks) o;
    return Objects.equals(this.numberOfDisk, abstractResultActionVirtualBackupForEntityWithDisks.numberOfDisk) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfDisk, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractResultActionVirtualBackupForEntityWithDisks {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    numberOfDisk: ").append(toIndentedString(numberOfDisk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
