/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.OperationState;
import com.vmware.safekeeping.cxf.rest.model.ResultAction;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * AbstractResultActionWithSubOperations
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class AbstractResultActionWithSubOperations extends ResultAction  {
  @JsonProperty("SubOperations")
  private List<SapiTask> subOperations = null;

  public AbstractResultActionWithSubOperations subOperations(List<SapiTask> subOperations) {
    this.subOperations = subOperations;
    return this;
  }

  public AbstractResultActionWithSubOperations addSubOperationsItem(SapiTask subOperationsItem) {
    if (this.subOperations == null) {
      this.subOperations = new ArrayList<SapiTask>();
    }
    this.subOperations.add(subOperationsItem);
    return this;
  }

  /**
   * Get subOperations
   * @return subOperations
   **/
  @JsonProperty("SubOperations")
  @Schema(description = "")
  @Valid
  public List<SapiTask> getSubOperations() {
    return subOperations;
  }

  public void setSubOperations(List<SapiTask> subOperations) {
    this.subOperations = subOperations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractResultActionWithSubOperations abstractResultActionWithSubOperations = (AbstractResultActionWithSubOperations) o;
    return Objects.equals(this.subOperations, abstractResultActionWithSubOperations.subOperations) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subOperations, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractResultActionWithSubOperations {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    subOperations: ").append(toIndentedString(subOperations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
