/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets BackupDiskPhases
 */
public enum BackupDiskPhases {
  NONE("NONE"),
    START("START"),
    START_OPEN_VMDK("START_OPEN_VMDK"),
    END_OPEN_VMDK("END_OPEN_VMDK"),
    START_QUERY_BLOCKS("START_QUERY_BLOCKS"),
    END_QUERY_BLOCKS("END_QUERY_BLOCKS"),
    START_NORMALIZE_VMDK_BLOCKS("START_NORMALIZE_VMDK_BLOCKS"),
    END_NORMALIZE_VMDK_BLOCKS("END_NORMALIZE_VMDK_BLOCKS"),
    START_DUMP_THREADS("START_DUMP_THREADS"),
    START_DUMPS_TOTAL_CALCULATION("START_DUMPS_TOTAL_CALCULATION"),
    END_DUMPS_TOTAL_CALCULATION("END_DUMPS_TOTAL_CALCULATION"),
    END_DUMP_THREADS("END_DUMP_THREADS"),
    START_CLOSE_VMDK("START_CLOSE_VMDK"),
    END_CLOSE_VMDK("END_CLOSE_VMDK"),
    END("END");

  private String value;

  BackupDiskPhases(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BackupDiskPhases fromValue(String text) {
    for (BackupDiskPhases b : BackupDiskPhases.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
