/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ConnectOptions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class ConnectOptions   {
  @JsonProperty("AuthServer")
  private String authServer = null;

  @JsonProperty("Base64")
  private Boolean base64 = null;

  public ConnectOptions authServer(String authServer) {
    this.authServer = authServer;
    return this;
  }

  /**
   * Get authServer
   * @return authServer
   **/
  @JsonProperty("AuthServer")
  @Schema(description = "")
  public String getAuthServer() {
    return authServer;
  }

  public void setAuthServer(String authServer) {
    this.authServer = authServer;
  }

  public ConnectOptions base64(Boolean base64) {
    this.base64 = base64;
    return this;
  }

  /**
   * Get base64
   * @return base64
   **/
  @JsonProperty("Base64")
  @Schema(description = "")
  public Boolean isBase64() {
    return base64;
  }

  public void setBase64(Boolean base64) {
    this.base64 = base64;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectOptions connectOptions = (ConnectOptions) o;
    return Objects.equals(this.authServer, connectOptions.authServer) &&
        Objects.equals(this.base64, connectOptions.base64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authServer, base64);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectOptions {\n");
    
    sb.append("    authServer: ").append(toIndentedString(authServer)).append("\n");
    sb.append("    base64: ").append(toIndentedString(base64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
