/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets EntityType
 */
public enum EntityType {
  NONE("None"),
    COMPUTERESOURCE("ComputeResource"),
    CLUSTERCOMPUTERESOURCE("ClusterComputeResource"),
    CONTAINERVIEW("ContainerView"),
    DATACENTER("Datacenter"),
    DATASTORE("Datastore"),
    VIRTUALIZATIONMANAGER("VirtualizationManager"),
    VIRTUALMACHINESNAPSHOT("VirtualMachineSnapshot"),
    VIRTUALMACHINE("VirtualMachine"),
    HOSTSYSTEM("HostSystem"),
    FOLDER("Folder"),
    VIRTUALAPP("VirtualApp"),
    RESOURCEPOOL("ResourcePool"),
    IMPROVEDVIRTUALDISK("ImprovedVirtualDisk"),
    K8SNAMESPACE("K8sNamespace"),
    NETWORK("Network"),
    OPAQUENETWORK("OpaqueNetwork"),
    DISTRIBUTEDVIRTUALPORTGROUP("DistributedVirtualPortgroup");

  private String value;

  EntityType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EntityType fromValue(String text) {
    for (EntityType b : EntityType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
