/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedEntityInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * FcoLocation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class FcoLocation   {
  @JsonProperty("DatacenterInfo")
  private ManagedEntityInfo datacenterInfo = null;

  public FcoLocation datacenterInfo(ManagedEntityInfo datacenterInfo) {
    this.datacenterInfo = datacenterInfo;
    return this;
  }

  /**
   * Get datacenterInfo
   * @return datacenterInfo
   **/
  @JsonProperty("DatacenterInfo")
  @Schema(description = "")
  @Valid
  public ManagedEntityInfo getDatacenterInfo() {
    return datacenterInfo;
  }

  public void setDatacenterInfo(ManagedEntityInfo datacenterInfo) {
    this.datacenterInfo = datacenterInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FcoLocation fcoLocation = (FcoLocation) o;
    return Objects.equals(this.datacenterInfo, fcoLocation.datacenterInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datacenterInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FcoLocation {\n");
    
    sb.append("    datacenterInfo: ").append(toIndentedString(datacenterInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
