/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.FcoTypeSearch;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * FcoTarget
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class FcoTarget   {
  @JsonProperty("Key")
  private String key = null;

  @JsonProperty("KeyType")
  private FcoTypeSearch keyType = null;

  @JsonProperty("VcenterUuid")
  private String vcenterUuid = null;

  public FcoTarget key(String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   **/
  @JsonProperty("Key")
  @Schema(description = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public FcoTarget keyType(FcoTypeSearch keyType) {
    this.keyType = keyType;
    return this;
  }

  /**
   * Get keyType
   * @return keyType
   **/
  @JsonProperty("KeyType")
  @Schema(description = "")
  @Valid
  public FcoTypeSearch getKeyType() {
    return keyType;
  }

  public void setKeyType(FcoTypeSearch keyType) {
    this.keyType = keyType;
  }

  public FcoTarget vcenterUuid(String vcenterUuid) {
    this.vcenterUuid = vcenterUuid;
    return this;
  }

  /**
   * Get vcenterUuid
   * @return vcenterUuid
   **/
  @JsonProperty("VcenterUuid")
  @Schema(description = "")
  public String getVcenterUuid() {
    return vcenterUuid;
  }

  public void setVcenterUuid(String vcenterUuid) {
    this.vcenterUuid = vcenterUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FcoTarget fcoTarget = (FcoTarget) o;
    return Objects.equals(this.key, fcoTarget.key) &&
        Objects.equals(this.keyType, fcoTarget.keyType) &&
        Objects.equals(this.vcenterUuid, fcoTarget.vcenterUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, keyType, vcenterUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FcoTarget {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    keyType: ").append(toIndentedString(keyType)).append("\n");
    sb.append("    vcenterUuid: ").append(toIndentedString(vcenterUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
