/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets FcoTypeSearch
 */
public enum FcoTypeSearch {
  IVD_NAME("IVD_NAME"),
    IVD_UUID("IVD_UUID"),
    TAG("TAG"),
    VAPP_NAME("VAPP_NAME"),
    VAPP_UUID("VAPP_UUID"),
    VAPP_MOREF("VAPP_MOREF"),
    VM_IP("VM_IP"),
    VM_MOREF("VM_MOREF"),
    VM_NAME("VM_NAME"),
    VM_UUID("VM_UUID"),
    K8S_NAME("K8S_NAME"),
    K8S_UUID("K8S_UUID");

  private String value;

  FcoTypeSearch(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FcoTypeSearch fromValue(String text) {
    for (FcoTypeSearch b : FcoTypeSearch.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
