/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.BackupMode;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GenerationInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")
public class GenerationInfo   {
  @JsonProperty("BackupMode")
  private BackupMode backupMode = null;

  @JsonProperty("GenerationId")
  private Integer generationId = null;

  @JsonProperty("PreviousGenerationId")
  private Integer previousGenerationId = null;

  @JsonProperty("TargetUri")
  private String targetUri = null;

  public GenerationInfo backupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
    return this;
  }

  /**
   * Get backupMode
   * @return backupMode
   **/
  @JsonProperty("BackupMode")
  @Schema(description = "")
  @Valid
  public BackupMode getBackupMode() {
    return backupMode;
  }

  public void setBackupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
  }

  public GenerationInfo generationId(Integer generationId) {
    this.generationId = generationId;
    return this;
  }

  /**
   * Get generationId
   * @return generationId
   **/
  @JsonProperty("GenerationId")
  @Schema(description = "")
  public Integer getGenerationId() {
    return generationId;
  }

  public void setGenerationId(Integer generationId) {
    this.generationId = generationId;
  }

  public GenerationInfo previousGenerationId(Integer previousGenerationId) {
    this.previousGenerationId = previousGenerationId;
    return this;
  }

  /**
   * Get previousGenerationId
   * @return previousGenerationId
   **/
  @JsonProperty("PreviousGenerationId")
  @Schema(description = "")
  public Integer getPreviousGenerationId() {
    return previousGenerationId;
  }

  public void setPreviousGenerationId(Integer previousGenerationId) {
    this.previousGenerationId = previousGenerationId;
  }

  public GenerationInfo targetUri(String targetUri) {
    this.targetUri = targetUri;
    return this;
  }

  /**
   * Get targetUri
   * @return targetUri
   **/
  @JsonProperty("TargetUri")
  @Schema(description = "")
  public String getTargetUri() {
    return targetUri;
  }

  public void setTargetUri(String targetUri) {
    this.targetUri = targetUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerationInfo generationInfo = (GenerationInfo) o;
    return Objects.equals(this.backupMode, generationInfo.backupMode) &&
        Objects.equals(this.generationId, generationInfo.generationId) &&
        Objects.equals(this.previousGenerationId, generationInfo.previousGenerationId) &&
        Objects.equals(this.targetUri, generationInfo.targetUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupMode, generationId, previousGenerationId, targetUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerationInfo {\n");
    
    sb.append("    backupMode: ").append(toIndentedString(backupMode)).append("\n");
    sb.append("    generationId: ").append(toIndentedString(generationId)).append("\n");
    sb.append("    previousGenerationId: ").append(toIndentedString(previousGenerationId)).append("\n");
    sb.append("    targetUri: ").append(toIndentedString(targetUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
