/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.EntityType;
import com.vmware.safekeeping.cxf.rest.model.GenerationStatusInfo;
import com.vmware.safekeeping.cxf.rest.model.StatusDiskInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GenerationDiskInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class GenerationDiskInfo extends GenerationStatusInfo  {
  @JsonProperty("DisksInfo")
  private StatusDiskInfo disksInfo = null;

  public GenerationDiskInfo disksInfo(StatusDiskInfo disksInfo) {
    this.disksInfo = disksInfo;
    return this;
  }

  /**
   * Get disksInfo
   * @return disksInfo
   **/
  @JsonProperty("DisksInfo")
  @Schema(description = "")
  @Valid
  public StatusDiskInfo getDisksInfo() {
    return disksInfo;
  }

  public void setDisksInfo(StatusDiskInfo disksInfo) {
    this.disksInfo = disksInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerationDiskInfo generationDiskInfo = (GenerationDiskInfo) o;
    return Objects.equals(this.disksInfo, generationDiskInfo.disksInfo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disksInfo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerationDiskInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    disksInfo: ").append(toIndentedString(disksInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
