/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.EntityType;
import com.vmware.safekeeping.cxf.rest.model.GenerationStatusInfo;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GenerationVirtualMachinesInfoList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class GenerationVirtualMachinesInfoList extends GenerationStatusInfo  {
  @JsonProperty("VmsInfoList")
  private List<ManagedFcoEntityInfo> vmsInfoList = null;

  public GenerationVirtualMachinesInfoList vmsInfoList(List<ManagedFcoEntityInfo> vmsInfoList) {
    this.vmsInfoList = vmsInfoList;
    return this;
  }

  public GenerationVirtualMachinesInfoList addVmsInfoListItem(ManagedFcoEntityInfo vmsInfoListItem) {
    if (this.vmsInfoList == null) {
      this.vmsInfoList = new ArrayList<ManagedFcoEntityInfo>();
    }
    this.vmsInfoList.add(vmsInfoListItem);
    return this;
  }

  /**
   * Get vmsInfoList
   * @return vmsInfoList
   **/
  @JsonProperty("VmsInfoList")
  @Schema(description = "")
  @Valid
  public List<ManagedFcoEntityInfo> getVmsInfoList() {
    return vmsInfoList;
  }

  public void setVmsInfoList(List<ManagedFcoEntityInfo> vmsInfoList) {
    this.vmsInfoList = vmsInfoList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerationVirtualMachinesInfoList generationVirtualMachinesInfoList = (GenerationVirtualMachinesInfoList) o;
    return Objects.equals(this.vmsInfoList, generationVirtualMachinesInfoList.vmsInfoList) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vmsInfoList, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerationVirtualMachinesInfoList {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    vmsInfoList: ").append(toIndentedString(vmsInfoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
