/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * GuestInfoFlags
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class GuestInfoFlags   {
  @JsonProperty("ChangeTrackingEnabled")
  private Boolean changeTrackingEnabled = null;

  @JsonProperty("ConfigurationEncrypted")
  private Boolean configurationEncrypted = null;

  @JsonProperty("DiskUuidEnabled")
  private Boolean diskUuidEnabled = null;

  @JsonProperty("GuestFullName")
  private String guestFullName = null;

  @JsonProperty("NumberOfVirtualDisk")
  private Integer numberOfVirtualDisk = null;

  @JsonProperty("VbsEnabled")
  private Boolean vbsEnabled = null;

  @JsonProperty("VmPathName")
  private String vmPathName = null;

  @JsonProperty("Template")
  private Boolean template = null;

  @JsonProperty("VAppConfigAvailable")
  private Boolean vappConfigAvailable = null;

  public GuestInfoFlags changeTrackingEnabled(Boolean changeTrackingEnabled) {
    this.changeTrackingEnabled = changeTrackingEnabled;
    return this;
  }

  /**
   * Get changeTrackingEnabled
   * @return changeTrackingEnabled
   **/
  @JsonProperty("ChangeTrackingEnabled")
  @Schema(description = "")
  public Boolean isChangeTrackingEnabled() {
    return changeTrackingEnabled;
  }

  public void setChangeTrackingEnabled(Boolean changeTrackingEnabled) {
    this.changeTrackingEnabled = changeTrackingEnabled;
  }

  public GuestInfoFlags configurationEncrypted(Boolean configurationEncrypted) {
    this.configurationEncrypted = configurationEncrypted;
    return this;
  }

  /**
   * Get configurationEncrypted
   * @return configurationEncrypted
   **/
  @JsonProperty("ConfigurationEncrypted")
  @Schema(description = "")
  public Boolean isConfigurationEncrypted() {
    return configurationEncrypted;
  }

  public void setConfigurationEncrypted(Boolean configurationEncrypted) {
    this.configurationEncrypted = configurationEncrypted;
  }

  public GuestInfoFlags diskUuidEnabled(Boolean diskUuidEnabled) {
    this.diskUuidEnabled = diskUuidEnabled;
    return this;
  }

  /**
   * Get diskUuidEnabled
   * @return diskUuidEnabled
   **/
  @JsonProperty("DiskUuidEnabled")
  @Schema(description = "")
  public Boolean isDiskUuidEnabled() {
    return diskUuidEnabled;
  }

  public void setDiskUuidEnabled(Boolean diskUuidEnabled) {
    this.diskUuidEnabled = diskUuidEnabled;
  }

  public GuestInfoFlags guestFullName(String guestFullName) {
    this.guestFullName = guestFullName;
    return this;
  }

  /**
   * Get guestFullName
   * @return guestFullName
   **/
  @JsonProperty("GuestFullName")
  @Schema(description = "")
  public String getGuestFullName() {
    return guestFullName;
  }

  public void setGuestFullName(String guestFullName) {
    this.guestFullName = guestFullName;
  }

  public GuestInfoFlags numberOfVirtualDisk(Integer numberOfVirtualDisk) {
    this.numberOfVirtualDisk = numberOfVirtualDisk;
    return this;
  }

  /**
   * Get numberOfVirtualDisk
   * @return numberOfVirtualDisk
   **/
  @JsonProperty("NumberOfVirtualDisk")
  @Schema(description = "")
  public Integer getNumberOfVirtualDisk() {
    return numberOfVirtualDisk;
  }

  public void setNumberOfVirtualDisk(Integer numberOfVirtualDisk) {
    this.numberOfVirtualDisk = numberOfVirtualDisk;
  }

  public GuestInfoFlags vbsEnabled(Boolean vbsEnabled) {
    this.vbsEnabled = vbsEnabled;
    return this;
  }

  /**
   * Get vbsEnabled
   * @return vbsEnabled
   **/
  @JsonProperty("VbsEnabled")
  @Schema(description = "")
  public Boolean isVbsEnabled() {
    return vbsEnabled;
  }

  public void setVbsEnabled(Boolean vbsEnabled) {
    this.vbsEnabled = vbsEnabled;
  }

  public GuestInfoFlags vmPathName(String vmPathName) {
    this.vmPathName = vmPathName;
    return this;
  }

  /**
   * Get vmPathName
   * @return vmPathName
   **/
  @JsonProperty("VmPathName")
  @Schema(description = "")
  public String getVmPathName() {
    return vmPathName;
  }

  public void setVmPathName(String vmPathName) {
    this.vmPathName = vmPathName;
  }

  public GuestInfoFlags template(Boolean template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   **/
  @JsonProperty("Template")
  @Schema(description = "")
  public Boolean isTemplate() {
    return template;
  }

  public void setTemplate(Boolean template) {
    this.template = template;
  }

  public GuestInfoFlags vappConfigAvailable(Boolean vappConfigAvailable) {
    this.vappConfigAvailable = vappConfigAvailable;
    return this;
  }

  /**
   * Get vappConfigAvailable
   * @return vappConfigAvailable
   **/
  @JsonProperty("VAppConfigAvailable")
  @Schema(description = "")
  public Boolean isVappConfigAvailable() {
    return vappConfigAvailable;
  }

  public void setVappConfigAvailable(Boolean vappConfigAvailable) {
    this.vappConfigAvailable = vappConfigAvailable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestInfoFlags guestInfoFlags = (GuestInfoFlags) o;
    return Objects.equals(this.changeTrackingEnabled, guestInfoFlags.changeTrackingEnabled) &&
        Objects.equals(this.configurationEncrypted, guestInfoFlags.configurationEncrypted) &&
        Objects.equals(this.diskUuidEnabled, guestInfoFlags.diskUuidEnabled) &&
        Objects.equals(this.guestFullName, guestInfoFlags.guestFullName) &&
        Objects.equals(this.numberOfVirtualDisk, guestInfoFlags.numberOfVirtualDisk) &&
        Objects.equals(this.vbsEnabled, guestInfoFlags.vbsEnabled) &&
        Objects.equals(this.vmPathName, guestInfoFlags.vmPathName) &&
        Objects.equals(this.template, guestInfoFlags.template) &&
        Objects.equals(this.vappConfigAvailable, guestInfoFlags.vappConfigAvailable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeTrackingEnabled, configurationEncrypted, diskUuidEnabled, guestFullName, numberOfVirtualDisk, vbsEnabled, vmPathName, template, vappConfigAvailable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestInfoFlags {\n");
    
    sb.append("    changeTrackingEnabled: ").append(toIndentedString(changeTrackingEnabled)).append("\n");
    sb.append("    configurationEncrypted: ").append(toIndentedString(configurationEncrypted)).append("\n");
    sb.append("    diskUuidEnabled: ").append(toIndentedString(diskUuidEnabled)).append("\n");
    sb.append("    guestFullName: ").append(toIndentedString(guestFullName)).append("\n");
    sb.append("    numberOfVirtualDisk: ").append(toIndentedString(numberOfVirtualDisk)).append("\n");
    sb.append("    vbsEnabled: ").append(toIndentedString(vbsEnabled)).append("\n");
    sb.append("    vmPathName: ").append(toIndentedString(vmPathName)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    vappConfigAvailable: ").append(toIndentedString(vappConfigAvailable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
