/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.EntityType;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ManagedEntityInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class ManagedEntityInfo   {
  @JsonProperty("EntityType")
  private EntityType entityType = null;

  @JsonProperty("MorefValue")
  private String morefValue = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("ServerUuid")
  private String serverUuid = null;

  public ManagedEntityInfo entityType(EntityType entityType) {
    this.entityType = entityType;
    return this;
  }

  /**
   * Get entityType
   * @return entityType
   **/
  @JsonProperty("EntityType")
  @Schema(description = "")
  @Valid
  public EntityType getEntityType() {
    return entityType;
  }

  public void setEntityType(EntityType entityType) {
    this.entityType = entityType;
  }

  public ManagedEntityInfo morefValue(String morefValue) {
    this.morefValue = morefValue;
    return this;
  }

  /**
   * Get morefValue
   * @return morefValue
   **/
  @JsonProperty("MorefValue")
  @Schema(description = "")
  public String getMorefValue() {
    return morefValue;
  }

  public void setMorefValue(String morefValue) {
    this.morefValue = morefValue;
  }

  public ManagedEntityInfo name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("Name")
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ManagedEntityInfo serverUuid(String serverUuid) {
    this.serverUuid = serverUuid;
    return this;
  }

  /**
   * Get serverUuid
   * @return serverUuid
   **/
  @JsonProperty("ServerUuid")
  @Schema(description = "")
  public String getServerUuid() {
    return serverUuid;
  }

  public void setServerUuid(String serverUuid) {
    this.serverUuid = serverUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagedEntityInfo managedEntityInfo = (ManagedEntityInfo) o;
    return Objects.equals(this.entityType, managedEntityInfo.entityType) &&
        Objects.equals(this.morefValue, managedEntityInfo.morefValue) &&
        Objects.equals(this.name, managedEntityInfo.name) &&
        Objects.equals(this.serverUuid, managedEntityInfo.serverUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityType, morefValue, name, serverUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagedEntityInfo {\n");
    
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    morefValue: ").append(toIndentedString(morefValue)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serverUuid: ").append(toIndentedString(serverUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
