/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets RemoveGenerationsPhases
 */
public enum RemoveGenerationsPhases {
  NONE("NONE"),
    START("START"),
    START_ACCESS_ARCHIVE("START_ACCESS_ARCHIVE"),
    END_ACCESS_ARCHIVE("END_ACCESS_ARCHIVE"),
    START_RETRIEVE_REQUESTED_GENERATIONS("START_RETRIEVE_REQUESTED_GENERATIONS"),
    END_RETRIEVE_REQUESTED_GENERATIONS("END_RETRIEVE_REQUESTED_GENERATIONS"),
    START_RETRIEVE_DEPENDING_GENERATIONS("START_RETRIEVE_DEPENDING_GENERATIONS"),
    END_RETRIEVE_DEPENDING_GENERATIONS("END_RETRIEVE_DEPENDING_GENERATIONS"),
    START_DELETE_GENERATIONS("START_DELETE_GENERATIONS"),
    START_DELETE_GENERATION("START_DELETE_GENERATION"),
    START_DELETE_DATA("START_DELETE_DATA"),
    END_DELETE_DATA("END_DELETE_DATA"),
    START_REMOVE_PROFILE_GENERATION("START_REMOVE_PROFILE_GENERATION"),
    END_REMOVE_PROFILE_GENERATION("END_REMOVE_PROFILE_GENERATION"),
    END_DELETE_GENERATION("END_DELETE_GENERATION"),
    END_DELETE_GENERATIONS("END_DELETE_GENERATIONS"),
    START_UPDATE_FCO_PROFILES_CATALOG("START_UPDATE_FCO_PROFILES_CATALOG"),
    END_UPDATE_FCO_PROFILES_CATALOG("END_UPDATE_FCO_PROFILES_CATALOG"),
    END("END");

  private String value;

  RemoveGenerationsPhases(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static RemoveGenerationsPhases fromValue(String text) {
    for (RemoveGenerationsPhases b : RemoveGenerationsPhases.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
