/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.SearchManagementEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RestoreVmdkOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class RestoreVmdkOption   {
  @JsonProperty("Datastore")
  private SearchManagementEntity datastore = null;

  @JsonProperty("DiskId")
  private Integer diskId = null;

  @JsonProperty("SpbmProfile")
  private SearchManagementEntity spbmProfile = null;

  public RestoreVmdkOption datastore(SearchManagementEntity datastore) {
    this.datastore = datastore;
    return this;
  }

  /**
   * Get datastore
   * @return datastore
   **/
  @JsonProperty("Datastore")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getDatastore() {
    return datastore;
  }

  public void setDatastore(SearchManagementEntity datastore) {
    this.datastore = datastore;
  }

  public RestoreVmdkOption diskId(Integer diskId) {
    this.diskId = diskId;
    return this;
  }

  /**
   * Get diskId
   * @return diskId
   **/
  @JsonProperty("DiskId")
  @Schema(description = "")
  public Integer getDiskId() {
    return diskId;
  }

  public void setDiskId(Integer diskId) {
    this.diskId = diskId;
  }

  public RestoreVmdkOption spbmProfile(SearchManagementEntity spbmProfile) {
    this.spbmProfile = spbmProfile;
    return this;
  }

  /**
   * Get spbmProfile
   * @return spbmProfile
   **/
  @JsonProperty("SpbmProfile")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getSpbmProfile() {
    return spbmProfile;
  }

  public void setSpbmProfile(SearchManagementEntity spbmProfile) {
    this.spbmProfile = spbmProfile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestoreVmdkOption restoreVmdkOption = (RestoreVmdkOption) o;
    return Objects.equals(this.datastore, restoreVmdkOption.datastore) &&
        Objects.equals(this.diskId, restoreVmdkOption.diskId) &&
        Objects.equals(this.spbmProfile, restoreVmdkOption.spbmProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datastore, diskId, spbmProfile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestoreVmdkOption {\n");
    
    sb.append("    datastore: ").append(toIndentedString(datastore)).append("\n");
    sb.append("    diskId: ").append(toIndentedString(diskId)).append("\n");
    sb.append("    spbmProfile: ").append(toIndentedString(spbmProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
