/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.BackupRestoreCommonOptions;
import com.vmware.safekeeping.cxf.rest.model.RestoreVmdkOption;
import com.vmware.safekeeping.cxf.rest.model.SearchManagementEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RestoreOptions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class RestoreOptions extends BackupRestoreCommonOptions  {
  @JsonProperty("Datacenter")
  private SearchManagementEntity datacenter = null;

  @JsonProperty("Datastore")
  private SearchManagementEntity datastore = null;

  @JsonProperty("Folder")
  private SearchManagementEntity folder = null;

  @JsonProperty("GenerationId")
  private Integer generationId = null;

  @JsonProperty("Host")
  private SearchManagementEntity host = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("Networks")
  private List<SearchManagementEntity> networks = null;

  @JsonProperty("Postfix")
  private String postfix = null;

  @JsonProperty("Prefix")
  private String prefix = null;

  @JsonProperty("RequestedTransportMode")
  private String requestedTransportMode = null;

  @JsonProperty("ResourcePool")
  private SearchManagementEntity resourcePool = null;

  @JsonProperty("ResPoolFilter")
  private String resPoolFilter = null;

  @JsonProperty("StorageProfile")
  private SearchManagementEntity storageProfile = null;

  @JsonProperty("VmFolderFilter")
  private String vmFolderFilter = null;

  @JsonProperty("AllowDuplicatedVmNamesInsideVapp")
  private Boolean allowDuplicatedVmNamesInsideVapp = null;

  @JsonProperty("ImportVmxFile")
  private Boolean importVmxFile = null;

  @JsonProperty("Overwrite")
  private Boolean overwrite = null;

  @JsonProperty("PowerOn")
  private Boolean powerOn = null;

  @JsonProperty("Recover")
  private Boolean recover = null;

  @JsonProperty("Disks")
  private List<RestoreVmdkOption> disks = null;

  public RestoreOptions datacenter(SearchManagementEntity datacenter) {
    this.datacenter = datacenter;
    return this;
  }

  /**
   * Get datacenter
   * @return datacenter
   **/
  @JsonProperty("Datacenter")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getDatacenter() {
    return datacenter;
  }

  public void setDatacenter(SearchManagementEntity datacenter) {
    this.datacenter = datacenter;
  }

  public RestoreOptions datastore(SearchManagementEntity datastore) {
    this.datastore = datastore;
    return this;
  }

  /**
   * Get datastore
   * @return datastore
   **/
  @JsonProperty("Datastore")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getDatastore() {
    return datastore;
  }

  public void setDatastore(SearchManagementEntity datastore) {
    this.datastore = datastore;
  }

  public RestoreOptions folder(SearchManagementEntity folder) {
    this.folder = folder;
    return this;
  }

  /**
   * Get folder
   * @return folder
   **/
  @JsonProperty("Folder")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getFolder() {
    return folder;
  }

  public void setFolder(SearchManagementEntity folder) {
    this.folder = folder;
  }

  public RestoreOptions generationId(Integer generationId) {
    this.generationId = generationId;
    return this;
  }

  /**
   * Get generationId
   * @return generationId
   **/
  @JsonProperty("GenerationId")
  @Schema(description = "")
  public Integer getGenerationId() {
    return generationId;
  }

  public void setGenerationId(Integer generationId) {
    this.generationId = generationId;
  }

  public RestoreOptions host(SearchManagementEntity host) {
    this.host = host;
    return this;
  }

  /**
   * Get host
   * @return host
   **/
  @JsonProperty("Host")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getHost() {
    return host;
  }

  public void setHost(SearchManagementEntity host) {
    this.host = host;
  }

  public RestoreOptions name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("Name")
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RestoreOptions networks(List<SearchManagementEntity> networks) {
    this.networks = networks;
    return this;
  }

  public RestoreOptions addNetworksItem(SearchManagementEntity networksItem) {
    if (this.networks == null) {
      this.networks = new ArrayList<SearchManagementEntity>();
    }
    this.networks.add(networksItem);
    return this;
  }

  /**
   * Get networks
   * @return networks
   **/
  @JsonProperty("Networks")
  @Schema(description = "")
  @Valid
  public List<SearchManagementEntity> getNetworks() {
    return networks;
  }

  public void setNetworks(List<SearchManagementEntity> networks) {
    this.networks = networks;
  }

  public RestoreOptions postfix(String postfix) {
    this.postfix = postfix;
    return this;
  }

  /**
   * Get postfix
   * @return postfix
   **/
  @JsonProperty("Postfix")
  @Schema(description = "")
  public String getPostfix() {
    return postfix;
  }

  public void setPostfix(String postfix) {
    this.postfix = postfix;
  }

  public RestoreOptions prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   **/
  @JsonProperty("Prefix")
  @Schema(description = "")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public RestoreOptions requestedTransportMode(String requestedTransportMode) {
    this.requestedTransportMode = requestedTransportMode;
    return this;
  }

  /**
   * Get requestedTransportMode
   * @return requestedTransportMode
   **/
  @JsonProperty("RequestedTransportMode")
  @Schema(description = "")
  public String getRequestedTransportMode() {
    return requestedTransportMode;
  }

  public void setRequestedTransportMode(String requestedTransportMode) {
    this.requestedTransportMode = requestedTransportMode;
  }

  public RestoreOptions resourcePool(SearchManagementEntity resourcePool) {
    this.resourcePool = resourcePool;
    return this;
  }

  /**
   * Get resourcePool
   * @return resourcePool
   **/
  @JsonProperty("ResourcePool")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getResourcePool() {
    return resourcePool;
  }

  public void setResourcePool(SearchManagementEntity resourcePool) {
    this.resourcePool = resourcePool;
  }

  public RestoreOptions resPoolFilter(String resPoolFilter) {
    this.resPoolFilter = resPoolFilter;
    return this;
  }

  /**
   * Get resPoolFilter
   * @return resPoolFilter
   **/
  @JsonProperty("ResPoolFilter")
  @Schema(description = "")
  public String getResPoolFilter() {
    return resPoolFilter;
  }

  public void setResPoolFilter(String resPoolFilter) {
    this.resPoolFilter = resPoolFilter;
  }

  public RestoreOptions storageProfile(SearchManagementEntity storageProfile) {
    this.storageProfile = storageProfile;
    return this;
  }

  /**
   * Get storageProfile
   * @return storageProfile
   **/
  @JsonProperty("StorageProfile")
  @Schema(description = "")
  @Valid
  public SearchManagementEntity getStorageProfile() {
    return storageProfile;
  }

  public void setStorageProfile(SearchManagementEntity storageProfile) {
    this.storageProfile = storageProfile;
  }

  public RestoreOptions vmFolderFilter(String vmFolderFilter) {
    this.vmFolderFilter = vmFolderFilter;
    return this;
  }

  /**
   * Get vmFolderFilter
   * @return vmFolderFilter
   **/
  @JsonProperty("VmFolderFilter")
  @Schema(description = "")
  public String getVmFolderFilter() {
    return vmFolderFilter;
  }

  public void setVmFolderFilter(String vmFolderFilter) {
    this.vmFolderFilter = vmFolderFilter;
  }

  public RestoreOptions allowDuplicatedVmNamesInsideVapp(Boolean allowDuplicatedVmNamesInsideVapp) {
    this.allowDuplicatedVmNamesInsideVapp = allowDuplicatedVmNamesInsideVapp;
    return this;
  }

  /**
   * Get allowDuplicatedVmNamesInsideVapp
   * @return allowDuplicatedVmNamesInsideVapp
   **/
  @JsonProperty("AllowDuplicatedVmNamesInsideVapp")
  @Schema(description = "")
  public Boolean isAllowDuplicatedVmNamesInsideVapp() {
    return allowDuplicatedVmNamesInsideVapp;
  }

  public void setAllowDuplicatedVmNamesInsideVapp(Boolean allowDuplicatedVmNamesInsideVapp) {
    this.allowDuplicatedVmNamesInsideVapp = allowDuplicatedVmNamesInsideVapp;
  }

  public RestoreOptions importVmxFile(Boolean importVmxFile) {
    this.importVmxFile = importVmxFile;
    return this;
  }

  /**
   * Get importVmxFile
   * @return importVmxFile
   **/
  @JsonProperty("ImportVmxFile")
  @Schema(description = "")
  public Boolean isImportVmxFile() {
    return importVmxFile;
  }

  public void setImportVmxFile(Boolean importVmxFile) {
    this.importVmxFile = importVmxFile;
  }

  public RestoreOptions overwrite(Boolean overwrite) {
    this.overwrite = overwrite;
    return this;
  }

  /**
   * Get overwrite
   * @return overwrite
   **/
  @JsonProperty("Overwrite")
  @Schema(description = "")
  public Boolean isOverwrite() {
    return overwrite;
  }

  public void setOverwrite(Boolean overwrite) {
    this.overwrite = overwrite;
  }

  public RestoreOptions powerOn(Boolean powerOn) {
    this.powerOn = powerOn;
    return this;
  }

  /**
   * Get powerOn
   * @return powerOn
   **/
  @JsonProperty("PowerOn")
  @Schema(description = "")
  public Boolean isPowerOn() {
    return powerOn;
  }

  public void setPowerOn(Boolean powerOn) {
    this.powerOn = powerOn;
  }

  public RestoreOptions recover(Boolean recover) {
    this.recover = recover;
    return this;
  }

  /**
   * Get recover
   * @return recover
   **/
  @JsonProperty("Recover")
  @Schema(description = "")
  public Boolean isRecover() {
    return recover;
  }

  public void setRecover(Boolean recover) {
    this.recover = recover;
  }

  public RestoreOptions disks(List<RestoreVmdkOption> disks) {
    this.disks = disks;
    return this;
  }

  public RestoreOptions addDisksItem(RestoreVmdkOption disksItem) {
    if (this.disks == null) {
      this.disks = new ArrayList<RestoreVmdkOption>();
    }
    this.disks.add(disksItem);
    return this;
  }

  /**
   * Get disks
   * @return disks
   **/
  @JsonProperty("Disks")
  @Schema(description = "")
  @Valid
  public List<RestoreVmdkOption> getDisks() {
    return disks;
  }

  public void setDisks(List<RestoreVmdkOption> disks) {
    this.disks = disks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestoreOptions restoreOptions = (RestoreOptions) o;
    return Objects.equals(this.datacenter, restoreOptions.datacenter) &&
        Objects.equals(this.datastore, restoreOptions.datastore) &&
        Objects.equals(this.folder, restoreOptions.folder) &&
        Objects.equals(this.generationId, restoreOptions.generationId) &&
        Objects.equals(this.host, restoreOptions.host) &&
        Objects.equals(this.name, restoreOptions.name) &&
        Objects.equals(this.networks, restoreOptions.networks) &&
        Objects.equals(this.postfix, restoreOptions.postfix) &&
        Objects.equals(this.prefix, restoreOptions.prefix) &&
        Objects.equals(this.requestedTransportMode, restoreOptions.requestedTransportMode) &&
        Objects.equals(this.resourcePool, restoreOptions.resourcePool) &&
        Objects.equals(this.resPoolFilter, restoreOptions.resPoolFilter) &&
        Objects.equals(this.storageProfile, restoreOptions.storageProfile) &&
        Objects.equals(this.vmFolderFilter, restoreOptions.vmFolderFilter) &&
        Objects.equals(this.allowDuplicatedVmNamesInsideVapp, restoreOptions.allowDuplicatedVmNamesInsideVapp) &&
        Objects.equals(this.importVmxFile, restoreOptions.importVmxFile) &&
        Objects.equals(this.overwrite, restoreOptions.overwrite) &&
        Objects.equals(this.powerOn, restoreOptions.powerOn) &&
        Objects.equals(this.recover, restoreOptions.recover) &&
        Objects.equals(this.disks, restoreOptions.disks) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datacenter, datastore, folder, generationId, host, name, networks, postfix, prefix, requestedTransportMode, resourcePool, resPoolFilter, storageProfile, vmFolderFilter, allowDuplicatedVmNamesInsideVapp, importVmxFile, overwrite, powerOn, recover, disks, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestoreOptions {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    datacenter: ").append(toIndentedString(datacenter)).append("\n");
    sb.append("    datastore: ").append(toIndentedString(datastore)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    generationId: ").append(toIndentedString(generationId)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    postfix: ").append(toIndentedString(postfix)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    requestedTransportMode: ").append(toIndentedString(requestedTransportMode)).append("\n");
    sb.append("    resourcePool: ").append(toIndentedString(resourcePool)).append("\n");
    sb.append("    resPoolFilter: ").append(toIndentedString(resPoolFilter)).append("\n");
    sb.append("    storageProfile: ").append(toIndentedString(storageProfile)).append("\n");
    sb.append("    vmFolderFilter: ").append(toIndentedString(vmFolderFilter)).append("\n");
    sb.append("    allowDuplicatedVmNamesInsideVapp: ").append(toIndentedString(allowDuplicatedVmNamesInsideVapp)).append("\n");
    sb.append("    importVmxFile: ").append(toIndentedString(importVmxFile)).append("\n");
    sb.append("    overwrite: ").append(toIndentedString(overwrite)).append("\n");
    sb.append("    powerOn: ").append(toIndentedString(powerOn)).append("\n");
    sb.append("    recover: ").append(toIndentedString(recover)).append("\n");
    sb.append("    disks: ").append(toIndentedString(disks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
