/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.RestoreManagedInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RestoreIvdManagedInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class RestoreIvdManagedInfo extends RestoreManagedInfo  {
  @JsonProperty("DatastoreInfo")
  private ManagedEntityInfo datastoreInfo = null;

  public RestoreIvdManagedInfo datastoreInfo(ManagedEntityInfo datastoreInfo) {
    this.datastoreInfo = datastoreInfo;
    return this;
  }

  /**
   * Get datastoreInfo
   * @return datastoreInfo
   **/
  @JsonProperty("DatastoreInfo")
  @Schema(description = "")
  @Valid
  public ManagedEntityInfo getDatastoreInfo() {
    return datastoreInfo;
  }

  public void setDatastoreInfo(ManagedEntityInfo datastoreInfo) {
    this.datastoreInfo = datastoreInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestoreIvdManagedInfo restoreIvdManagedInfo = (RestoreIvdManagedInfo) o;
    return Objects.equals(this.datastoreInfo, restoreIvdManagedInfo.datastoreInfo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datastoreInfo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestoreIvdManagedInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    datastoreInfo: ").append(toIndentedString(datastoreInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
