/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedEntityInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * RestoreManagedInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class RestoreManagedInfo   {
  @JsonProperty("DcInfo")
  private ManagedEntityInfo dcInfo = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("SpbmProfile")
  private List<String> spbmProfile = null;

  @JsonProperty("Recovery")
  private Boolean recovery = null;

  public RestoreManagedInfo dcInfo(ManagedEntityInfo dcInfo) {
    this.dcInfo = dcInfo;
    return this;
  }

  /**
   * Get dcInfo
   * @return dcInfo
   **/
  @JsonProperty("DcInfo")
  @Schema(description = "")
  @Valid
  public ManagedEntityInfo getDcInfo() {
    return dcInfo;
  }

  public void setDcInfo(ManagedEntityInfo dcInfo) {
    this.dcInfo = dcInfo;
  }

  public RestoreManagedInfo name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("Name")
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RestoreManagedInfo spbmProfile(List<String> spbmProfile) {
    this.spbmProfile = spbmProfile;
    return this;
  }

  public RestoreManagedInfo addSpbmProfileItem(String spbmProfileItem) {
    if (this.spbmProfile == null) {
      this.spbmProfile = new ArrayList<String>();
    }
    this.spbmProfile.add(spbmProfileItem);
    return this;
  }

  /**
   * Get spbmProfile
   * @return spbmProfile
   **/
  @JsonProperty("SpbmProfile")
  @Schema(description = "")
  public List<String> getSpbmProfile() {
    return spbmProfile;
  }

  public void setSpbmProfile(List<String> spbmProfile) {
    this.spbmProfile = spbmProfile;
  }

  public RestoreManagedInfo recovery(Boolean recovery) {
    this.recovery = recovery;
    return this;
  }

  /**
   * Get recovery
   * @return recovery
   **/
  @JsonProperty("Recovery")
  @Schema(description = "")
  public Boolean isRecovery() {
    return recovery;
  }

  public void setRecovery(Boolean recovery) {
    this.recovery = recovery;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestoreManagedInfo restoreManagedInfo = (RestoreManagedInfo) o;
    return Objects.equals(this.dcInfo, restoreManagedInfo.dcInfo) &&
        Objects.equals(this.name, restoreManagedInfo.name) &&
        Objects.equals(this.spbmProfile, restoreManagedInfo.spbmProfile) &&
        Objects.equals(this.recovery, restoreManagedInfo.recovery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dcInfo, name, spbmProfile, recovery);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestoreManagedInfo {\n");
    
    sb.append("    dcInfo: ").append(toIndentedString(dcInfo)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    spbmProfile: ").append(toIndentedString(spbmProfile)).append("\n");
    sb.append("    recovery: ").append(toIndentedString(recovery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
