/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AbstractResultActionArchive;
import com.vmware.safekeeping.cxf.rest.model.StatusProfilePhases;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionArchiveStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class ResultActionArchiveStatus extends AbstractResultActionArchive  {
  @JsonProperty("GenerationList")
  private List<Integer> generationList = null;

  @JsonProperty("GenerationStatus")
  private String generationStatus = null;

  @JsonProperty("LatestSucceededGenerationId")
  private Integer latestSucceededGenerationId = null;

  @JsonProperty("NumOfGeneration")
  private Integer numOfGeneration = null;

  @JsonProperty("NumOfSuccceededGeneration")
  private Integer numOfSuccceededGeneration = null;

  @JsonProperty("Phase")
  private StatusProfilePhases phase = null;

  @JsonProperty("Available")
  private Boolean available = null;

  @JsonProperty("Empty")
  private Boolean empty = null;

  public ResultActionArchiveStatus generationList(List<Integer> generationList) {
    this.generationList = generationList;
    return this;
  }

  public ResultActionArchiveStatus addGenerationListItem(Integer generationListItem) {
    if (this.generationList == null) {
      this.generationList = new ArrayList<Integer>();
    }
    this.generationList.add(generationListItem);
    return this;
  }

  /**
   * Get generationList
   * @return generationList
   **/
  @JsonProperty("GenerationList")
  @Schema(description = "")
  public List<Integer> getGenerationList() {
    return generationList;
  }

  public void setGenerationList(List<Integer> generationList) {
    this.generationList = generationList;
  }

  public ResultActionArchiveStatus generationStatus(String generationStatus) {
    this.generationStatus = generationStatus;
    return this;
  }

  /**
   * Get generationStatus
   * @return generationStatus
   **/
  @JsonProperty("GenerationStatus")
  @Schema(description = "")
  public String getGenerationStatus() {
    return generationStatus;
  }

  public void setGenerationStatus(String generationStatus) {
    this.generationStatus = generationStatus;
  }

  public ResultActionArchiveStatus latestSucceededGenerationId(Integer latestSucceededGenerationId) {
    this.latestSucceededGenerationId = latestSucceededGenerationId;
    return this;
  }

  /**
   * Get latestSucceededGenerationId
   * @return latestSucceededGenerationId
   **/
  @JsonProperty("LatestSucceededGenerationId")
  @Schema(description = "")
  public Integer getLatestSucceededGenerationId() {
    return latestSucceededGenerationId;
  }

  public void setLatestSucceededGenerationId(Integer latestSucceededGenerationId) {
    this.latestSucceededGenerationId = latestSucceededGenerationId;
  }

  public ResultActionArchiveStatus numOfGeneration(Integer numOfGeneration) {
    this.numOfGeneration = numOfGeneration;
    return this;
  }

  /**
   * Get numOfGeneration
   * @return numOfGeneration
   **/
  @JsonProperty("NumOfGeneration")
  @Schema(description = "")
  public Integer getNumOfGeneration() {
    return numOfGeneration;
  }

  public void setNumOfGeneration(Integer numOfGeneration) {
    this.numOfGeneration = numOfGeneration;
  }

  public ResultActionArchiveStatus numOfSuccceededGeneration(Integer numOfSuccceededGeneration) {
    this.numOfSuccceededGeneration = numOfSuccceededGeneration;
    return this;
  }

  /**
   * Get numOfSuccceededGeneration
   * @return numOfSuccceededGeneration
   **/
  @JsonProperty("NumOfSuccceededGeneration")
  @Schema(description = "")
  public Integer getNumOfSuccceededGeneration() {
    return numOfSuccceededGeneration;
  }

  public void setNumOfSuccceededGeneration(Integer numOfSuccceededGeneration) {
    this.numOfSuccceededGeneration = numOfSuccceededGeneration;
  }

  public ResultActionArchiveStatus phase(StatusProfilePhases phase) {
    this.phase = phase;
    return this;
  }

  /**
   * Get phase
   * @return phase
   **/
  @JsonProperty("Phase")
  @Schema(description = "")
  @Valid
  public StatusProfilePhases getPhase() {
    return phase;
  }

  public void setPhase(StatusProfilePhases phase) {
    this.phase = phase;
  }

  public ResultActionArchiveStatus available(Boolean available) {
    this.available = available;
    return this;
  }

  /**
   * Get available
   * @return available
   **/
  @JsonProperty("Available")
  @Schema(description = "")
  public Boolean isAvailable() {
    return available;
  }

  public void setAvailable(Boolean available) {
    this.available = available;
  }

  public ResultActionArchiveStatus empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

  /**
   * Get empty
   * @return empty
   **/
  @JsonProperty("Empty")
  @Schema(description = "")
  public Boolean isEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionArchiveStatus resultActionArchiveStatus = (ResultActionArchiveStatus) o;
    return Objects.equals(this.generationList, resultActionArchiveStatus.generationList) &&
        Objects.equals(this.generationStatus, resultActionArchiveStatus.generationStatus) &&
        Objects.equals(this.latestSucceededGenerationId, resultActionArchiveStatus.latestSucceededGenerationId) &&
        Objects.equals(this.numOfGeneration, resultActionArchiveStatus.numOfGeneration) &&
        Objects.equals(this.numOfSuccceededGeneration, resultActionArchiveStatus.numOfSuccceededGeneration) &&
        Objects.equals(this.phase, resultActionArchiveStatus.phase) &&
        Objects.equals(this.available, resultActionArchiveStatus.available) &&
        Objects.equals(this.empty, resultActionArchiveStatus.empty) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generationList, generationStatus, latestSucceededGenerationId, numOfGeneration, numOfSuccceededGeneration, phase, available, empty, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionArchiveStatus {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    generationList: ").append(toIndentedString(generationList)).append("\n");
    sb.append("    generationStatus: ").append(toIndentedString(generationStatus)).append("\n");
    sb.append("    latestSucceededGenerationId: ").append(toIndentedString(latestSucceededGenerationId)).append("\n");
    sb.append("    numOfGeneration: ").append(toIndentedString(numOfGeneration)).append("\n");
    sb.append("    numOfSuccceededGeneration: ").append(toIndentedString(numOfSuccceededGeneration)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
