/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.OperationState;
import com.vmware.safekeeping.cxf.rest.model.ResultAction;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionDisconnect
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class ResultActionDisconnect extends ResultAction implements OneOfTaskResultResult  {
  @JsonProperty("SubTasksActionConnectVCenters")
  private List<SapiTask> subTasksActionConnectVCenters = null;

  @JsonProperty("Connected")
  private Boolean connected = null;

  public ResultActionDisconnect subTasksActionConnectVCenters(List<SapiTask> subTasksActionConnectVCenters) {
    this.subTasksActionConnectVCenters = subTasksActionConnectVCenters;
    return this;
  }

  public ResultActionDisconnect addSubTasksActionConnectVCentersItem(SapiTask subTasksActionConnectVCentersItem) {
    if (this.subTasksActionConnectVCenters == null) {
      this.subTasksActionConnectVCenters = new ArrayList<SapiTask>();
    }
    this.subTasksActionConnectVCenters.add(subTasksActionConnectVCentersItem);
    return this;
  }

  /**
   * Get subTasksActionConnectVCenters
   * @return subTasksActionConnectVCenters
   **/
  @JsonProperty("SubTasksActionConnectVCenters")
  @Schema(description = "")
  @Valid
  public List<SapiTask> getSubTasksActionConnectVCenters() {
    return subTasksActionConnectVCenters;
  }

  public void setSubTasksActionConnectVCenters(List<SapiTask> subTasksActionConnectVCenters) {
    this.subTasksActionConnectVCenters = subTasksActionConnectVCenters;
  }

  public ResultActionDisconnect connected(Boolean connected) {
    this.connected = connected;
    return this;
  }

  /**
   * Get connected
   * @return connected
   **/
  @JsonProperty("Connected")
  @Schema(description = "")
  public Boolean isConnected() {
    return connected;
  }

  public void setConnected(Boolean connected) {
    this.connected = connected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionDisconnect resultActionDisconnect = (ResultActionDisconnect) o;
    return Objects.equals(this.subTasksActionConnectVCenters, resultActionDisconnect.subTasksActionConnectVCenters) &&
        Objects.equals(this.connected, resultActionDisconnect.connected) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subTasksActionConnectVCenters, connected, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionDisconnect {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    subTasksActionConnectVCenters: ").append(toIndentedString(subTasksActionConnectVCenters)).append("\n");
    sb.append("    connected: ").append(toIndentedString(connected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
