/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ExtensionManagerOperation;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.OperationState;
import com.vmware.safekeeping.cxf.rest.model.ResultAction;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionExtension
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class ResultActionExtension extends ResultAction implements OneOfTaskResultResult  {
  @JsonProperty("Operation")
  private ExtensionManagerOperation operation = null;

  @JsonProperty("Version")
  private String version = null;

  @JsonProperty("HealthInfo")
  private Boolean healthInfo = null;

  public ResultActionExtension operation(ExtensionManagerOperation operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Get operation
   * @return operation
   **/
  @JsonProperty("Operation")
  @Schema(description = "")
  @Valid
  public ExtensionManagerOperation getOperation() {
    return operation;
  }

  public void setOperation(ExtensionManagerOperation operation) {
    this.operation = operation;
  }

  public ResultActionExtension version(String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   **/
  @JsonProperty("Version")
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ResultActionExtension healthInfo(Boolean healthInfo) {
    this.healthInfo = healthInfo;
    return this;
  }

  /**
   * Get healthInfo
   * @return healthInfo
   **/
  @JsonProperty("HealthInfo")
  @Schema(description = "")
  public Boolean isHealthInfo() {
    return healthInfo;
  }

  public void setHealthInfo(Boolean healthInfo) {
    this.healthInfo = healthInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionExtension resultActionExtension = (ResultActionExtension) o;
    return Objects.equals(this.operation, resultActionExtension.operation) &&
        Objects.equals(this.version, resultActionExtension.version) &&
        Objects.equals(this.healthInfo, resultActionExtension.healthInfo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, version, healthInfo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionExtension {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    healthInfo: ").append(toIndentedString(healthInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
