/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.OperationState;
import com.vmware.safekeeping.cxf.rest.model.ResultAction;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionDisconnectVcenter
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class ResultActionDisconnectVcenter extends ResultAction implements OneOfTaskResultResult  {
  @JsonProperty("Api")
  private String api = null;

  @JsonProperty("InstanceUuid")
  private String instanceUuid = null;

  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("PbmUrl")
  private String pbmUrl = null;

  @JsonProperty("PbmVersion")
  private String pbmVersion = null;

  @JsonProperty("Url")
  private String url = null;

  @JsonProperty("VapiUrl")
  private String vapiUrl = null;

  @JsonProperty("VslmName")
  private String vslmName = null;

  @JsonProperty("VslmUrl")
  private String vslmUrl = null;

  @JsonProperty("PbmConnected")
  private Boolean pbmConnected = null;

  @JsonProperty("VapiConnected")
  private Boolean vapiConnected = null;

  @JsonProperty("VslmConnected")
  private Boolean vslmConnected = null;

  public ResultActionDisconnectVcenter api(String api) {
    this.api = api;
    return this;
  }

  /**
   * Get api
   * @return api
   **/
  @JsonProperty("Api")
  @Schema(description = "")
  public String getApi() {
    return api;
  }

  public void setApi(String api) {
    this.api = api;
  }

  public ResultActionDisconnectVcenter instanceUuid(String instanceUuid) {
    this.instanceUuid = instanceUuid;
    return this;
  }

  /**
   * Get instanceUuid
   * @return instanceUuid
   **/
  @JsonProperty("InstanceUuid")
  @Schema(description = "")
  public String getInstanceUuid() {
    return instanceUuid;
  }

  public void setInstanceUuid(String instanceUuid) {
    this.instanceUuid = instanceUuid;
  }

  public ResultActionDisconnectVcenter name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("Name")
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResultActionDisconnectVcenter pbmUrl(String pbmUrl) {
    this.pbmUrl = pbmUrl;
    return this;
  }

  /**
   * Get pbmUrl
   * @return pbmUrl
   **/
  @JsonProperty("PbmUrl")
  @Schema(description = "")
  public String getPbmUrl() {
    return pbmUrl;
  }

  public void setPbmUrl(String pbmUrl) {
    this.pbmUrl = pbmUrl;
  }

  public ResultActionDisconnectVcenter pbmVersion(String pbmVersion) {
    this.pbmVersion = pbmVersion;
    return this;
  }

  /**
   * Get pbmVersion
   * @return pbmVersion
   **/
  @JsonProperty("PbmVersion")
  @Schema(description = "")
  public String getPbmVersion() {
    return pbmVersion;
  }

  public void setPbmVersion(String pbmVersion) {
    this.pbmVersion = pbmVersion;
  }

  public ResultActionDisconnectVcenter url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   **/
  @JsonProperty("Url")
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ResultActionDisconnectVcenter vapiUrl(String vapiUrl) {
    this.vapiUrl = vapiUrl;
    return this;
  }

  /**
   * Get vapiUrl
   * @return vapiUrl
   **/
  @JsonProperty("VapiUrl")
  @Schema(description = "")
  public String getVapiUrl() {
    return vapiUrl;
  }

  public void setVapiUrl(String vapiUrl) {
    this.vapiUrl = vapiUrl;
  }

  public ResultActionDisconnectVcenter vslmName(String vslmName) {
    this.vslmName = vslmName;
    return this;
  }

  /**
   * Get vslmName
   * @return vslmName
   **/
  @JsonProperty("VslmName")
  @Schema(description = "")
  public String getVslmName() {
    return vslmName;
  }

  public void setVslmName(String vslmName) {
    this.vslmName = vslmName;
  }

  public ResultActionDisconnectVcenter vslmUrl(String vslmUrl) {
    this.vslmUrl = vslmUrl;
    return this;
  }

  /**
   * Get vslmUrl
   * @return vslmUrl
   **/
  @JsonProperty("VslmUrl")
  @Schema(description = "")
  public String getVslmUrl() {
    return vslmUrl;
  }

  public void setVslmUrl(String vslmUrl) {
    this.vslmUrl = vslmUrl;
  }

  public ResultActionDisconnectVcenter pbmConnected(Boolean pbmConnected) {
    this.pbmConnected = pbmConnected;
    return this;
  }

  /**
   * Get pbmConnected
   * @return pbmConnected
   **/
  @JsonProperty("PbmConnected")
  @Schema(description = "")
  public Boolean isPbmConnected() {
    return pbmConnected;
  }

  public void setPbmConnected(Boolean pbmConnected) {
    this.pbmConnected = pbmConnected;
  }

  public ResultActionDisconnectVcenter vapiConnected(Boolean vapiConnected) {
    this.vapiConnected = vapiConnected;
    return this;
  }

  /**
   * Get vapiConnected
   * @return vapiConnected
   **/
  @JsonProperty("VapiConnected")
  @Schema(description = "")
  public Boolean isVapiConnected() {
    return vapiConnected;
  }

  public void setVapiConnected(Boolean vapiConnected) {
    this.vapiConnected = vapiConnected;
  }

  public ResultActionDisconnectVcenter vslmConnected(Boolean vslmConnected) {
    this.vslmConnected = vslmConnected;
    return this;
  }

  /**
   * Get vslmConnected
   * @return vslmConnected
   **/
  @JsonProperty("VslmConnected")
  @Schema(description = "")
  public Boolean isVslmConnected() {
    return vslmConnected;
  }

  public void setVslmConnected(Boolean vslmConnected) {
    this.vslmConnected = vslmConnected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionDisconnectVcenter resultActionDisconnectVcenter = (ResultActionDisconnectVcenter) o;
    return Objects.equals(this.api, resultActionDisconnectVcenter.api) &&
        Objects.equals(this.instanceUuid, resultActionDisconnectVcenter.instanceUuid) &&
        Objects.equals(this.name, resultActionDisconnectVcenter.name) &&
        Objects.equals(this.pbmUrl, resultActionDisconnectVcenter.pbmUrl) &&
        Objects.equals(this.pbmVersion, resultActionDisconnectVcenter.pbmVersion) &&
        Objects.equals(this.url, resultActionDisconnectVcenter.url) &&
        Objects.equals(this.vapiUrl, resultActionDisconnectVcenter.vapiUrl) &&
        Objects.equals(this.vslmName, resultActionDisconnectVcenter.vslmName) &&
        Objects.equals(this.vslmUrl, resultActionDisconnectVcenter.vslmUrl) &&
        Objects.equals(this.pbmConnected, resultActionDisconnectVcenter.pbmConnected) &&
        Objects.equals(this.vapiConnected, resultActionDisconnectVcenter.vapiConnected) &&
        Objects.equals(this.vslmConnected, resultActionDisconnectVcenter.vslmConnected) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(api, instanceUuid, name, pbmUrl, pbmVersion, url, vapiUrl, vslmName, vslmUrl, pbmConnected, vapiConnected, vslmConnected, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionDisconnectVcenter {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    api: ").append(toIndentedString(api)).append("\n");
    sb.append("    instanceUuid: ").append(toIndentedString(instanceUuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pbmUrl: ").append(toIndentedString(pbmUrl)).append("\n");
    sb.append("    pbmVersion: ").append(toIndentedString(pbmVersion)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    vapiUrl: ").append(toIndentedString(vapiUrl)).append("\n");
    sb.append("    vslmName: ").append(toIndentedString(vslmName)).append("\n");
    sb.append("    vslmUrl: ").append(toIndentedString(vslmUrl)).append("\n");
    sb.append("    pbmConnected: ").append(toIndentedString(pbmConnected)).append("\n");
    sb.append("    vapiConnected: ").append(toIndentedString(vapiConnected)).append("\n");
    sb.append("    vslmConnected: ").append(toIndentedString(vslmConnected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
