/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AbstractResultActionBackupForEntityWithDisks;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionIvdBackup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class ResultActionIvdBackup extends AbstractResultActionBackupForEntityWithDisks implements OneOfTaskResultResult  {
  @JsonProperty("ResultActionOnDisk")
  private SapiTask resultActionOnDisk = null;

  public ResultActionIvdBackup resultActionOnDisk(SapiTask resultActionOnDisk) {
    this.resultActionOnDisk = resultActionOnDisk;
    return this;
  }

  /**
   * Get resultActionOnDisk
   * @return resultActionOnDisk
   **/
  @JsonProperty("ResultActionOnDisk")
  @Schema(description = "")
  @Valid
  public SapiTask getResultActionOnDisk() {
    return resultActionOnDisk;
  }

  public void setResultActionOnDisk(SapiTask resultActionOnDisk) {
    this.resultActionOnDisk = resultActionOnDisk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionIvdBackup resultActionIvdBackup = (ResultActionIvdBackup) o;
    return Objects.equals(this.resultActionOnDisk, resultActionIvdBackup.resultActionOnDisk) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultActionOnDisk, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionIvdBackup {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    resultActionOnDisk: ").append(toIndentedString(resultActionOnDisk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
