/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.OperationState;
import com.vmware.safekeeping.cxf.rest.model.ResultAction;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionConnectSso
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class ResultActionConnectSso extends ResultAction implements OneOfTaskResultResult  {
  @JsonProperty("SsoEndPointUrl")
  private String ssoEndPointUrl = null;

  @JsonProperty("Token")
  private String token = null;

  @JsonProperty("Connected")
  private Boolean connected = null;

  public ResultActionConnectSso ssoEndPointUrl(String ssoEndPointUrl) {
    this.ssoEndPointUrl = ssoEndPointUrl;
    return this;
  }

  /**
   * Get ssoEndPointUrl
   * @return ssoEndPointUrl
   **/
  @JsonProperty("SsoEndPointUrl")
  @Schema(description = "")
  public String getSsoEndPointUrl() {
    return ssoEndPointUrl;
  }

  public void setSsoEndPointUrl(String ssoEndPointUrl) {
    this.ssoEndPointUrl = ssoEndPointUrl;
  }

  public ResultActionConnectSso token(String token) {
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   **/
  @JsonProperty("Token")
  @Schema(description = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public ResultActionConnectSso connected(Boolean connected) {
    this.connected = connected;
    return this;
  }

  /**
   * Get connected
   * @return connected
   **/
  @JsonProperty("Connected")
  @Schema(description = "")
  public Boolean isConnected() {
    return connected;
  }

  public void setConnected(Boolean connected) {
    this.connected = connected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionConnectSso resultActionConnectSso = (ResultActionConnectSso) o;
    return Objects.equals(this.ssoEndPointUrl, resultActionConnectSso.ssoEndPointUrl) &&
        Objects.equals(this.token, resultActionConnectSso.token) &&
        Objects.equals(this.connected, resultActionConnectSso.connected) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ssoEndPointUrl, token, connected, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionConnectSso {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    ssoEndPointUrl: ").append(toIndentedString(ssoEndPointUrl)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    connected: ").append(toIndentedString(connected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
