/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AbstractResultActionBackupRestore;
import com.vmware.safekeeping.cxf.rest.model.BackupMode;
import com.vmware.safekeeping.cxf.rest.model.FcoLocation;
import com.vmware.safekeeping.cxf.rest.model.GenerationInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionBackup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class ResultActionBackup extends AbstractResultActionBackupRestore  {
  @JsonProperty("BackupMode")
  private BackupMode backupMode = null;

  @JsonProperty("CbtEnabled")
  private Boolean cbtEnabled = null;

  public ResultActionBackup backupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
    return this;
  }

  /**
   * Get backupMode
   * @return backupMode
   **/
  @JsonProperty("BackupMode")
  @Schema(description = "")
  @Valid
  public BackupMode getBackupMode() {
    return backupMode;
  }

  public void setBackupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
  }

  public ResultActionBackup cbtEnabled(Boolean cbtEnabled) {
    this.cbtEnabled = cbtEnabled;
    return this;
  }

  /**
   * Get cbtEnabled
   * @return cbtEnabled
   **/
  @JsonProperty("CbtEnabled")
  @Schema(description = "")
  public Boolean isCbtEnabled() {
    return cbtEnabled;
  }

  public void setCbtEnabled(Boolean cbtEnabled) {
    this.cbtEnabled = cbtEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionBackup resultActionBackup = (ResultActionBackup) o;
    return Objects.equals(this.backupMode, resultActionBackup.backupMode) &&
        Objects.equals(this.cbtEnabled, resultActionBackup.cbtEnabled) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupMode, cbtEnabled, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionBackup {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    backupMode: ").append(toIndentedString(backupMode)).append("\n");
    sb.append("    cbtEnabled: ").append(toIndentedString(cbtEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
