/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AbstractResultActionRestoreForEntityWithDisks;
import com.vmware.safekeeping.cxf.rest.model.GuestInfoFlags;
import com.vmware.safekeeping.cxf.rest.model.ManagedFcoEntityInfo;
import com.vmware.safekeeping.cxf.rest.model.RestoreVmManagedInfo;
import com.vmware.safekeeping.cxf.rest.model.SapiTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ResultActionVmRestore
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class ResultActionVmRestore extends AbstractResultActionRestoreForEntityWithDisks implements OneOfTaskResultResult  {
  @JsonProperty("FcoChildren")
  private List<ManagedFcoEntityInfo> fcoChildren = null;

  @JsonProperty("GuestFlags")
  private GuestInfoFlags guestFlags = null;

  @JsonProperty("ManagedInfo")
  private RestoreVmManagedInfo managedInfo = null;

  @JsonProperty("NumberOfChildVm")
  private Integer numberOfChildVm = null;

  @JsonProperty("ResultActionOnChildVms")
  private List<SapiTask> resultActionOnChildVms = null;

  @JsonProperty("ResultActionsOnDisk")
  private List<SapiTask> resultActionsOnDisk = null;

  @JsonProperty("Template")
  private Boolean template = null;

  public ResultActionVmRestore fcoChildren(List<ManagedFcoEntityInfo> fcoChildren) {
    this.fcoChildren = fcoChildren;
    return this;
  }

  public ResultActionVmRestore addFcoChildrenItem(ManagedFcoEntityInfo fcoChildrenItem) {
    if (this.fcoChildren == null) {
      this.fcoChildren = new ArrayList<ManagedFcoEntityInfo>();
    }
    this.fcoChildren.add(fcoChildrenItem);
    return this;
  }

  /**
   * Get fcoChildren
   * @return fcoChildren
   **/
  @JsonProperty("FcoChildren")
  @Schema(description = "")
  @Valid
  public List<ManagedFcoEntityInfo> getFcoChildren() {
    return fcoChildren;
  }

  public void setFcoChildren(List<ManagedFcoEntityInfo> fcoChildren) {
    this.fcoChildren = fcoChildren;
  }

  public ResultActionVmRestore guestFlags(GuestInfoFlags guestFlags) {
    this.guestFlags = guestFlags;
    return this;
  }

  /**
   * Get guestFlags
   * @return guestFlags
   **/
  @JsonProperty("GuestFlags")
  @Schema(description = "")
  @Valid
  public GuestInfoFlags getGuestFlags() {
    return guestFlags;
  }

  public void setGuestFlags(GuestInfoFlags guestFlags) {
    this.guestFlags = guestFlags;
  }

  public ResultActionVmRestore managedInfo(RestoreVmManagedInfo managedInfo) {
    this.managedInfo = managedInfo;
    return this;
  }

  /**
   * Get managedInfo
   * @return managedInfo
   **/
  @JsonProperty("ManagedInfo")
  @Schema(description = "")
  @Valid
  public RestoreVmManagedInfo getManagedInfo() {
    return managedInfo;
  }

  public void setManagedInfo(RestoreVmManagedInfo managedInfo) {
    this.managedInfo = managedInfo;
  }

  public ResultActionVmRestore numberOfChildVm(Integer numberOfChildVm) {
    this.numberOfChildVm = numberOfChildVm;
    return this;
  }

  /**
   * Get numberOfChildVm
   * @return numberOfChildVm
   **/
  @JsonProperty("NumberOfChildVm")
  @Schema(description = "")
  public Integer getNumberOfChildVm() {
    return numberOfChildVm;
  }

  public void setNumberOfChildVm(Integer numberOfChildVm) {
    this.numberOfChildVm = numberOfChildVm;
  }

  public ResultActionVmRestore resultActionOnChildVms(List<SapiTask> resultActionOnChildVms) {
    this.resultActionOnChildVms = resultActionOnChildVms;
    return this;
  }

  public ResultActionVmRestore addResultActionOnChildVmsItem(SapiTask resultActionOnChildVmsItem) {
    if (this.resultActionOnChildVms == null) {
      this.resultActionOnChildVms = new ArrayList<SapiTask>();
    }
    this.resultActionOnChildVms.add(resultActionOnChildVmsItem);
    return this;
  }

  /**
   * Get resultActionOnChildVms
   * @return resultActionOnChildVms
   **/
  @JsonProperty("ResultActionOnChildVms")
  @Schema(description = "")
  @Valid
  public List<SapiTask> getResultActionOnChildVms() {
    return resultActionOnChildVms;
  }

  public void setResultActionOnChildVms(List<SapiTask> resultActionOnChildVms) {
    this.resultActionOnChildVms = resultActionOnChildVms;
  }

  public ResultActionVmRestore resultActionsOnDisk(List<SapiTask> resultActionsOnDisk) {
    this.resultActionsOnDisk = resultActionsOnDisk;
    return this;
  }

  public ResultActionVmRestore addResultActionsOnDiskItem(SapiTask resultActionsOnDiskItem) {
    if (this.resultActionsOnDisk == null) {
      this.resultActionsOnDisk = new ArrayList<SapiTask>();
    }
    this.resultActionsOnDisk.add(resultActionsOnDiskItem);
    return this;
  }

  /**
   * Get resultActionsOnDisk
   * @return resultActionsOnDisk
   **/
  @JsonProperty("ResultActionsOnDisk")
  @Schema(description = "")
  @Valid
  public List<SapiTask> getResultActionsOnDisk() {
    return resultActionsOnDisk;
  }

  public void setResultActionsOnDisk(List<SapiTask> resultActionsOnDisk) {
    this.resultActionsOnDisk = resultActionsOnDisk;
  }

  public ResultActionVmRestore template(Boolean template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   **/
  @JsonProperty("Template")
  @Schema(description = "")
  public Boolean isTemplate() {
    return template;
  }

  public void setTemplate(Boolean template) {
    this.template = template;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultActionVmRestore resultActionVmRestore = (ResultActionVmRestore) o;
    return Objects.equals(this.fcoChildren, resultActionVmRestore.fcoChildren) &&
        Objects.equals(this.guestFlags, resultActionVmRestore.guestFlags) &&
        Objects.equals(this.managedInfo, resultActionVmRestore.managedInfo) &&
        Objects.equals(this.numberOfChildVm, resultActionVmRestore.numberOfChildVm) &&
        Objects.equals(this.resultActionOnChildVms, resultActionVmRestore.resultActionOnChildVms) &&
        Objects.equals(this.resultActionsOnDisk, resultActionVmRestore.resultActionsOnDisk) &&
        Objects.equals(this.template, resultActionVmRestore.template) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fcoChildren, guestFlags, managedInfo, numberOfChildVm, resultActionOnChildVms, resultActionsOnDisk, template, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultActionVmRestore {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fcoChildren: ").append(toIndentedString(fcoChildren)).append("\n");
    sb.append("    guestFlags: ").append(toIndentedString(guestFlags)).append("\n");
    sb.append("    managedInfo: ").append(toIndentedString(managedInfo)).append("\n");
    sb.append("    numberOfChildVm: ").append(toIndentedString(numberOfChildVm)).append("\n");
    sb.append("    resultActionOnChildVms: ").append(toIndentedString(resultActionOnChildVms)).append("\n");
    sb.append("    resultActionsOnDisk: ").append(toIndentedString(resultActionsOnDisk)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
