/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SerializableVAppIPAssignmentInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class SerializableVAppIPAssignmentInfo   {
  @JsonProperty("IpAllocationPolicy")
  private String ipAllocationPolicy = null;

  @JsonProperty("IpProtocol")
  private String ipProtocol = null;

  @JsonProperty("SupportedAllocationScheme")
  private List<String> supportedAllocationScheme = null;

  @JsonProperty("SupportedIpProtocol")
  private List<String> supportedIpProtocol = null;

  public SerializableVAppIPAssignmentInfo ipAllocationPolicy(String ipAllocationPolicy) {
    this.ipAllocationPolicy = ipAllocationPolicy;
    return this;
  }

  /**
   * Get ipAllocationPolicy
   * @return ipAllocationPolicy
   **/
  @JsonProperty("IpAllocationPolicy")
  @Schema(description = "")
  public String getIpAllocationPolicy() {
    return ipAllocationPolicy;
  }

  public void setIpAllocationPolicy(String ipAllocationPolicy) {
    this.ipAllocationPolicy = ipAllocationPolicy;
  }

  public SerializableVAppIPAssignmentInfo ipProtocol(String ipProtocol) {
    this.ipProtocol = ipProtocol;
    return this;
  }

  /**
   * Get ipProtocol
   * @return ipProtocol
   **/
  @JsonProperty("IpProtocol")
  @Schema(description = "")
  public String getIpProtocol() {
    return ipProtocol;
  }

  public void setIpProtocol(String ipProtocol) {
    this.ipProtocol = ipProtocol;
  }

  public SerializableVAppIPAssignmentInfo supportedAllocationScheme(List<String> supportedAllocationScheme) {
    this.supportedAllocationScheme = supportedAllocationScheme;
    return this;
  }

  public SerializableVAppIPAssignmentInfo addSupportedAllocationSchemeItem(String supportedAllocationSchemeItem) {
    if (this.supportedAllocationScheme == null) {
      this.supportedAllocationScheme = new ArrayList<String>();
    }
    this.supportedAllocationScheme.add(supportedAllocationSchemeItem);
    return this;
  }

  /**
   * Get supportedAllocationScheme
   * @return supportedAllocationScheme
   **/
  @JsonProperty("SupportedAllocationScheme")
  @Schema(description = "")
  public List<String> getSupportedAllocationScheme() {
    return supportedAllocationScheme;
  }

  public void setSupportedAllocationScheme(List<String> supportedAllocationScheme) {
    this.supportedAllocationScheme = supportedAllocationScheme;
  }

  public SerializableVAppIPAssignmentInfo supportedIpProtocol(List<String> supportedIpProtocol) {
    this.supportedIpProtocol = supportedIpProtocol;
    return this;
  }

  public SerializableVAppIPAssignmentInfo addSupportedIpProtocolItem(String supportedIpProtocolItem) {
    if (this.supportedIpProtocol == null) {
      this.supportedIpProtocol = new ArrayList<String>();
    }
    this.supportedIpProtocol.add(supportedIpProtocolItem);
    return this;
  }

  /**
   * Get supportedIpProtocol
   * @return supportedIpProtocol
   **/
  @JsonProperty("SupportedIpProtocol")
  @Schema(description = "")
  public List<String> getSupportedIpProtocol() {
    return supportedIpProtocol;
  }

  public void setSupportedIpProtocol(List<String> supportedIpProtocol) {
    this.supportedIpProtocol = supportedIpProtocol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SerializableVAppIPAssignmentInfo serializableVAppIPAssignmentInfo = (SerializableVAppIPAssignmentInfo) o;
    return Objects.equals(this.ipAllocationPolicy, serializableVAppIPAssignmentInfo.ipAllocationPolicy) &&
        Objects.equals(this.ipProtocol, serializableVAppIPAssignmentInfo.ipProtocol) &&
        Objects.equals(this.supportedAllocationScheme, serializableVAppIPAssignmentInfo.supportedAllocationScheme) &&
        Objects.equals(this.supportedIpProtocol, serializableVAppIPAssignmentInfo.supportedIpProtocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipAllocationPolicy, ipProtocol, supportedAllocationScheme, supportedIpProtocol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SerializableVAppIPAssignmentInfo {\n");
    
    sb.append("    ipAllocationPolicy: ").append(toIndentedString(ipAllocationPolicy)).append("\n");
    sb.append("    ipProtocol: ").append(toIndentedString(ipProtocol)).append("\n");
    sb.append("    supportedAllocationScheme: ").append(toIndentedString(supportedAllocationScheme)).append("\n");
    sb.append("    supportedIpProtocol: ").append(toIndentedString(supportedIpProtocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
