/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.SerializableVAppIPAssignmentInfo;
import com.vmware.safekeeping.cxf.rest.model.SerializableVAppOvfSectionInfo;
import com.vmware.safekeeping.cxf.rest.model.SerializableVAppProductInfo;
import com.vmware.safekeeping.cxf.rest.model.SerializableVAppPropertyInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SerializableVmConfigInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class SerializableVmConfigInfo   {
  @JsonProperty("Eula")
  private List<String> eula = null;

  @JsonProperty("InstallBootStopDelay")
  private Integer installBootStopDelay = null;

  @JsonProperty("IpAssignment")
  private SerializableVAppIPAssignmentInfo ipAssignment = null;

  @JsonProperty("OvfEnvironmentTransport")
  private List<String> ovfEnvironmentTransport = null;

  @JsonProperty("OvfSection")
  private List<SerializableVAppOvfSectionInfo> ovfSection = null;

  @JsonProperty("Product")
  private List<SerializableVAppProductInfo> product = null;

  @JsonProperty("Property")
  private List<SerializableVAppPropertyInfo> property = null;

  @JsonProperty("InstallBootRequired")
  private Boolean installBootRequired = null;

  public SerializableVmConfigInfo eula(List<String> eula) {
    this.eula = eula;
    return this;
  }

  public SerializableVmConfigInfo addEulaItem(String eulaItem) {
    if (this.eula == null) {
      this.eula = new ArrayList<String>();
    }
    this.eula.add(eulaItem);
    return this;
  }

  /**
   * Get eula
   * @return eula
   **/
  @JsonProperty("Eula")
  @Schema(description = "")
  public List<String> getEula() {
    return eula;
  }

  public void setEula(List<String> eula) {
    this.eula = eula;
  }

  public SerializableVmConfigInfo installBootStopDelay(Integer installBootStopDelay) {
    this.installBootStopDelay = installBootStopDelay;
    return this;
  }

  /**
   * Get installBootStopDelay
   * @return installBootStopDelay
   **/
  @JsonProperty("InstallBootStopDelay")
  @Schema(description = "")
  public Integer getInstallBootStopDelay() {
    return installBootStopDelay;
  }

  public void setInstallBootStopDelay(Integer installBootStopDelay) {
    this.installBootStopDelay = installBootStopDelay;
  }

  public SerializableVmConfigInfo ipAssignment(SerializableVAppIPAssignmentInfo ipAssignment) {
    this.ipAssignment = ipAssignment;
    return this;
  }

  /**
   * Get ipAssignment
   * @return ipAssignment
   **/
  @JsonProperty("IpAssignment")
  @Schema(description = "")
  @Valid
  public SerializableVAppIPAssignmentInfo getIpAssignment() {
    return ipAssignment;
  }

  public void setIpAssignment(SerializableVAppIPAssignmentInfo ipAssignment) {
    this.ipAssignment = ipAssignment;
  }

  public SerializableVmConfigInfo ovfEnvironmentTransport(List<String> ovfEnvironmentTransport) {
    this.ovfEnvironmentTransport = ovfEnvironmentTransport;
    return this;
  }

  public SerializableVmConfigInfo addOvfEnvironmentTransportItem(String ovfEnvironmentTransportItem) {
    if (this.ovfEnvironmentTransport == null) {
      this.ovfEnvironmentTransport = new ArrayList<String>();
    }
    this.ovfEnvironmentTransport.add(ovfEnvironmentTransportItem);
    return this;
  }

  /**
   * Get ovfEnvironmentTransport
   * @return ovfEnvironmentTransport
   **/
  @JsonProperty("OvfEnvironmentTransport")
  @Schema(description = "")
  public List<String> getOvfEnvironmentTransport() {
    return ovfEnvironmentTransport;
  }

  public void setOvfEnvironmentTransport(List<String> ovfEnvironmentTransport) {
    this.ovfEnvironmentTransport = ovfEnvironmentTransport;
  }

  public SerializableVmConfigInfo ovfSection(List<SerializableVAppOvfSectionInfo> ovfSection) {
    this.ovfSection = ovfSection;
    return this;
  }

  public SerializableVmConfigInfo addOvfSectionItem(SerializableVAppOvfSectionInfo ovfSectionItem) {
    if (this.ovfSection == null) {
      this.ovfSection = new ArrayList<SerializableVAppOvfSectionInfo>();
    }
    this.ovfSection.add(ovfSectionItem);
    return this;
  }

  /**
   * Get ovfSection
   * @return ovfSection
   **/
  @JsonProperty("OvfSection")
  @Schema(description = "")
  @Valid
  public List<SerializableVAppOvfSectionInfo> getOvfSection() {
    return ovfSection;
  }

  public void setOvfSection(List<SerializableVAppOvfSectionInfo> ovfSection) {
    this.ovfSection = ovfSection;
  }

  public SerializableVmConfigInfo product(List<SerializableVAppProductInfo> product) {
    this.product = product;
    return this;
  }

  public SerializableVmConfigInfo addProductItem(SerializableVAppProductInfo productItem) {
    if (this.product == null) {
      this.product = new ArrayList<SerializableVAppProductInfo>();
    }
    this.product.add(productItem);
    return this;
  }

  /**
   * Get product
   * @return product
   **/
  @JsonProperty("Product")
  @Schema(description = "")
  @Valid
  public List<SerializableVAppProductInfo> getProduct() {
    return product;
  }

  public void setProduct(List<SerializableVAppProductInfo> product) {
    this.product = product;
  }

  public SerializableVmConfigInfo property(List<SerializableVAppPropertyInfo> property) {
    this.property = property;
    return this;
  }

  public SerializableVmConfigInfo addPropertyItem(SerializableVAppPropertyInfo propertyItem) {
    if (this.property == null) {
      this.property = new ArrayList<SerializableVAppPropertyInfo>();
    }
    this.property.add(propertyItem);
    return this;
  }

  /**
   * Get property
   * @return property
   **/
  @JsonProperty("Property")
  @Schema(description = "")
  @Valid
  public List<SerializableVAppPropertyInfo> getProperty() {
    return property;
  }

  public void setProperty(List<SerializableVAppPropertyInfo> property) {
    this.property = property;
  }

  public SerializableVmConfigInfo installBootRequired(Boolean installBootRequired) {
    this.installBootRequired = installBootRequired;
    return this;
  }

  /**
   * Get installBootRequired
   * @return installBootRequired
   **/
  @JsonProperty("InstallBootRequired")
  @Schema(description = "")
  public Boolean isInstallBootRequired() {
    return installBootRequired;
  }

  public void setInstallBootRequired(Boolean installBootRequired) {
    this.installBootRequired = installBootRequired;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SerializableVmConfigInfo serializableVmConfigInfo = (SerializableVmConfigInfo) o;
    return Objects.equals(this.eula, serializableVmConfigInfo.eula) &&
        Objects.equals(this.installBootStopDelay, serializableVmConfigInfo.installBootStopDelay) &&
        Objects.equals(this.ipAssignment, serializableVmConfigInfo.ipAssignment) &&
        Objects.equals(this.ovfEnvironmentTransport, serializableVmConfigInfo.ovfEnvironmentTransport) &&
        Objects.equals(this.ovfSection, serializableVmConfigInfo.ovfSection) &&
        Objects.equals(this.product, serializableVmConfigInfo.product) &&
        Objects.equals(this.property, serializableVmConfigInfo.property) &&
        Objects.equals(this.installBootRequired, serializableVmConfigInfo.installBootRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eula, installBootStopDelay, ipAssignment, ovfEnvironmentTransport, ovfSection, product, property, installBootRequired);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SerializableVmConfigInfo {\n");
    
    sb.append("    eula: ").append(toIndentedString(eula)).append("\n");
    sb.append("    installBootStopDelay: ").append(toIndentedString(installBootStopDelay)).append("\n");
    sb.append("    ipAssignment: ").append(toIndentedString(ipAssignment)).append("\n");
    sb.append("    ovfEnvironmentTransport: ").append(toIndentedString(ovfEnvironmentTransport)).append("\n");
    sb.append("    ovfSection: ").append(toIndentedString(ovfSection)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    installBootRequired: ").append(toIndentedString(installBootRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
