/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.EntityType;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SerializableVAppEntityConfigInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class SerializableVAppEntityConfigInfo   {
  @JsonProperty("DestroyWithParent")
  private Boolean destroyWithParent = null;

  @JsonProperty("Key")
  private String key = null;

  @JsonProperty("StartAction")
  private String startAction = null;

  @JsonProperty("StartDelay")
  private Integer startDelay = null;

  @JsonProperty("StartOrder")
  private Integer startOrder = null;

  @JsonProperty("StopAction")
  private String stopAction = null;

  @JsonProperty("StopDelay")
  private Integer stopDelay = null;

  @JsonProperty("Tag")
  private String tag = null;

  @JsonProperty("Type")
  private EntityType type = null;

  @JsonProperty("WaitingForGuest")
  private Boolean waitingForGuest = null;

  public SerializableVAppEntityConfigInfo destroyWithParent(Boolean destroyWithParent) {
    this.destroyWithParent = destroyWithParent;
    return this;
  }

  /**
   * Get destroyWithParent
   * @return destroyWithParent
   **/
  @JsonProperty("DestroyWithParent")
  @Schema(description = "")
  public Boolean isDestroyWithParent() {
    return destroyWithParent;
  }

  public void setDestroyWithParent(Boolean destroyWithParent) {
    this.destroyWithParent = destroyWithParent;
  }

  public SerializableVAppEntityConfigInfo key(String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   **/
  @JsonProperty("Key")
  @Schema(description = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public SerializableVAppEntityConfigInfo startAction(String startAction) {
    this.startAction = startAction;
    return this;
  }

  /**
   * Get startAction
   * @return startAction
   **/
  @JsonProperty("StartAction")
  @Schema(description = "")
  public String getStartAction() {
    return startAction;
  }

  public void setStartAction(String startAction) {
    this.startAction = startAction;
  }

  public SerializableVAppEntityConfigInfo startDelay(Integer startDelay) {
    this.startDelay = startDelay;
    return this;
  }

  /**
   * Get startDelay
   * @return startDelay
   **/
  @JsonProperty("StartDelay")
  @Schema(description = "")
  public Integer getStartDelay() {
    return startDelay;
  }

  public void setStartDelay(Integer startDelay) {
    this.startDelay = startDelay;
  }

  public SerializableVAppEntityConfigInfo startOrder(Integer startOrder) {
    this.startOrder = startOrder;
    return this;
  }

  /**
   * Get startOrder
   * @return startOrder
   **/
  @JsonProperty("StartOrder")
  @Schema(description = "")
  public Integer getStartOrder() {
    return startOrder;
  }

  public void setStartOrder(Integer startOrder) {
    this.startOrder = startOrder;
  }

  public SerializableVAppEntityConfigInfo stopAction(String stopAction) {
    this.stopAction = stopAction;
    return this;
  }

  /**
   * Get stopAction
   * @return stopAction
   **/
  @JsonProperty("StopAction")
  @Schema(description = "")
  public String getStopAction() {
    return stopAction;
  }

  public void setStopAction(String stopAction) {
    this.stopAction = stopAction;
  }

  public SerializableVAppEntityConfigInfo stopDelay(Integer stopDelay) {
    this.stopDelay = stopDelay;
    return this;
  }

  /**
   * Get stopDelay
   * @return stopDelay
   **/
  @JsonProperty("StopDelay")
  @Schema(description = "")
  public Integer getStopDelay() {
    return stopDelay;
  }

  public void setStopDelay(Integer stopDelay) {
    this.stopDelay = stopDelay;
  }

  public SerializableVAppEntityConfigInfo tag(String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   **/
  @JsonProperty("Tag")
  @Schema(description = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public SerializableVAppEntityConfigInfo type(EntityType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   **/
  @JsonProperty("Type")
  @Schema(description = "")
  @Valid
  public EntityType getType() {
    return type;
  }

  public void setType(EntityType type) {
    this.type = type;
  }

  public SerializableVAppEntityConfigInfo waitingForGuest(Boolean waitingForGuest) {
    this.waitingForGuest = waitingForGuest;
    return this;
  }

  /**
   * Get waitingForGuest
   * @return waitingForGuest
   **/
  @JsonProperty("WaitingForGuest")
  @Schema(description = "")
  public Boolean isWaitingForGuest() {
    return waitingForGuest;
  }

  public void setWaitingForGuest(Boolean waitingForGuest) {
    this.waitingForGuest = waitingForGuest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SerializableVAppEntityConfigInfo serializableVAppEntityConfigInfo = (SerializableVAppEntityConfigInfo) o;
    return Objects.equals(this.destroyWithParent, serializableVAppEntityConfigInfo.destroyWithParent) &&
        Objects.equals(this.key, serializableVAppEntityConfigInfo.key) &&
        Objects.equals(this.startAction, serializableVAppEntityConfigInfo.startAction) &&
        Objects.equals(this.startDelay, serializableVAppEntityConfigInfo.startDelay) &&
        Objects.equals(this.startOrder, serializableVAppEntityConfigInfo.startOrder) &&
        Objects.equals(this.stopAction, serializableVAppEntityConfigInfo.stopAction) &&
        Objects.equals(this.stopDelay, serializableVAppEntityConfigInfo.stopDelay) &&
        Objects.equals(this.tag, serializableVAppEntityConfigInfo.tag) &&
        Objects.equals(this.type, serializableVAppEntityConfigInfo.type) &&
        Objects.equals(this.waitingForGuest, serializableVAppEntityConfigInfo.waitingForGuest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destroyWithParent, key, startAction, startDelay, startOrder, stopAction, stopDelay, tag, type, waitingForGuest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SerializableVAppEntityConfigInfo {\n");
    
    sb.append("    destroyWithParent: ").append(toIndentedString(destroyWithParent)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    startAction: ").append(toIndentedString(startAction)).append("\n");
    sb.append("    startDelay: ").append(toIndentedString(startDelay)).append("\n");
    sb.append("    startOrder: ").append(toIndentedString(startOrder)).append("\n");
    sb.append("    stopAction: ").append(toIndentedString(stopAction)).append("\n");
    sb.append("    stopDelay: ").append(toIndentedString(stopDelay)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    waitingForGuest: ").append(toIndentedString(waitingForGuest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
