/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * ServerInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class ServerInfo   {
  @JsonProperty("BigEndianBiosUuid")
  private String bigEndianBiosUuid = null;

  @JsonProperty("ExtendedVersion")
  private String extendedVersion = null;

  @JsonProperty("Hostname")
  private String hostname = null;

  @JsonProperty("ServerBiosUuid")
  private String serverBiosUuid = null;

  @JsonProperty("ServerIp")
  private String serverIp = null;

  @JsonProperty("ServerOs")
  private String serverOs = null;

  public ServerInfo bigEndianBiosUuid(String bigEndianBiosUuid) {
    this.bigEndianBiosUuid = bigEndianBiosUuid;
    return this;
  }

  /**
   * Get bigEndianBiosUuid
   * @return bigEndianBiosUuid
   **/
  @JsonProperty("BigEndianBiosUuid")
  @Schema(description = "")
  public String getBigEndianBiosUuid() {
    return bigEndianBiosUuid;
  }

  public void setBigEndianBiosUuid(String bigEndianBiosUuid) {
    this.bigEndianBiosUuid = bigEndianBiosUuid;
  }

  public ServerInfo extendedVersion(String extendedVersion) {
    this.extendedVersion = extendedVersion;
    return this;
  }

  /**
   * Get extendedVersion
   * @return extendedVersion
   **/
  @JsonProperty("ExtendedVersion")
  @Schema(description = "")
  public String getExtendedVersion() {
    return extendedVersion;
  }

  public void setExtendedVersion(String extendedVersion) {
    this.extendedVersion = extendedVersion;
  }

  public ServerInfo hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

  /**
   * Get hostname
   * @return hostname
   **/
  @JsonProperty("Hostname")
  @Schema(description = "")
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public ServerInfo serverBiosUuid(String serverBiosUuid) {
    this.serverBiosUuid = serverBiosUuid;
    return this;
  }

  /**
   * Get serverBiosUuid
   * @return serverBiosUuid
   **/
  @JsonProperty("ServerBiosUuid")
  @Schema(description = "")
  public String getServerBiosUuid() {
    return serverBiosUuid;
  }

  public void setServerBiosUuid(String serverBiosUuid) {
    this.serverBiosUuid = serverBiosUuid;
  }

  public ServerInfo serverIp(String serverIp) {
    this.serverIp = serverIp;
    return this;
  }

  /**
   * Get serverIp
   * @return serverIp
   **/
  @JsonProperty("ServerIp")
  @Schema(description = "")
  public String getServerIp() {
    return serverIp;
  }

  public void setServerIp(String serverIp) {
    this.serverIp = serverIp;
  }

  public ServerInfo serverOs(String serverOs) {
    this.serverOs = serverOs;
    return this;
  }

  /**
   * Get serverOs
   * @return serverOs
   **/
  @JsonProperty("ServerOs")
  @Schema(description = "")
  public String getServerOs() {
    return serverOs;
  }

  public void setServerOs(String serverOs) {
    this.serverOs = serverOs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerInfo serverInfo = (ServerInfo) o;
    return Objects.equals(this.bigEndianBiosUuid, serverInfo.bigEndianBiosUuid) &&
        Objects.equals(this.extendedVersion, serverInfo.extendedVersion) &&
        Objects.equals(this.hostname, serverInfo.hostname) &&
        Objects.equals(this.serverBiosUuid, serverInfo.serverBiosUuid) &&
        Objects.equals(this.serverIp, serverInfo.serverIp) &&
        Objects.equals(this.serverOs, serverInfo.serverOs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bigEndianBiosUuid, extendedVersion, hostname, serverBiosUuid, serverIp, serverOs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerInfo {\n");
    
    sb.append("    bigEndianBiosUuid: ").append(toIndentedString(bigEndianBiosUuid)).append("\n");
    sb.append("    extendedVersion: ").append(toIndentedString(extendedVersion)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    serverBiosUuid: ").append(toIndentedString(serverBiosUuid)).append("\n");
    sb.append("    serverIp: ").append(toIndentedString(serverIp)).append("\n");
    sb.append("    serverOs: ").append(toIndentedString(serverOs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
