/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.AdapterType;
import com.vmware.safekeeping.cxf.rest.model.BackupMode;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * StatusVirtualMachineDiskInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class StatusVirtualMachineDiskInfo   {
  @JsonProperty("AdapterType")
  private AdapterType adapterType = null;

  @JsonProperty("BusNumber")
  private Integer busNumber = null;

  @JsonProperty("ControllerDeviceKey")
  private Integer controllerDeviceKey = null;

  @JsonProperty("UnitNumber")
  private Integer unitNumber = null;

  @JsonProperty("BackupMode")
  private BackupMode backupMode = null;

  @JsonProperty("Capacity")
  private Long capacity = null;

  @JsonProperty("DiskId")
  private Integer diskId = null;

  @JsonProperty("DumpElapsedTimeMs")
  private Long dumpElapsedTimeMs = null;

  public StatusVirtualMachineDiskInfo adapterType(AdapterType adapterType) {
    this.adapterType = adapterType;
    return this;
  }

  /**
   * Get adapterType
   * @return adapterType
   **/
  @JsonProperty("AdapterType")
  @Schema(description = "")
  @Valid
  public AdapterType getAdapterType() {
    return adapterType;
  }

  public void setAdapterType(AdapterType adapterType) {
    this.adapterType = adapterType;
  }

  public StatusVirtualMachineDiskInfo busNumber(Integer busNumber) {
    this.busNumber = busNumber;
    return this;
  }

  /**
   * Get busNumber
   * @return busNumber
   **/
  @JsonProperty("BusNumber")
  @Schema(description = "")
  public Integer getBusNumber() {
    return busNumber;
  }

  public void setBusNumber(Integer busNumber) {
    this.busNumber = busNumber;
  }

  public StatusVirtualMachineDiskInfo controllerDeviceKey(Integer controllerDeviceKey) {
    this.controllerDeviceKey = controllerDeviceKey;
    return this;
  }

  /**
   * Get controllerDeviceKey
   * @return controllerDeviceKey
   **/
  @JsonProperty("ControllerDeviceKey")
  @Schema(description = "")
  public Integer getControllerDeviceKey() {
    return controllerDeviceKey;
  }

  public void setControllerDeviceKey(Integer controllerDeviceKey) {
    this.controllerDeviceKey = controllerDeviceKey;
  }

  public StatusVirtualMachineDiskInfo unitNumber(Integer unitNumber) {
    this.unitNumber = unitNumber;
    return this;
  }

  /**
   * Get unitNumber
   * @return unitNumber
   **/
  @JsonProperty("UnitNumber")
  @Schema(description = "")
  public Integer getUnitNumber() {
    return unitNumber;
  }

  public void setUnitNumber(Integer unitNumber) {
    this.unitNumber = unitNumber;
  }

  public StatusVirtualMachineDiskInfo backupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
    return this;
  }

  /**
   * Get backupMode
   * @return backupMode
   **/
  @JsonProperty("BackupMode")
  @Schema(description = "")
  @Valid
  public BackupMode getBackupMode() {
    return backupMode;
  }

  public void setBackupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
  }

  public StatusVirtualMachineDiskInfo capacity(Long capacity) {
    this.capacity = capacity;
    return this;
  }

  /**
   * Get capacity
   * @return capacity
   **/
  @JsonProperty("Capacity")
  @Schema(description = "")
  public Long getCapacity() {
    return capacity;
  }

  public void setCapacity(Long capacity) {
    this.capacity = capacity;
  }

  public StatusVirtualMachineDiskInfo diskId(Integer diskId) {
    this.diskId = diskId;
    return this;
  }

  /**
   * Get diskId
   * @return diskId
   **/
  @JsonProperty("DiskId")
  @Schema(description = "")
  public Integer getDiskId() {
    return diskId;
  }

  public void setDiskId(Integer diskId) {
    this.diskId = diskId;
  }

  public StatusVirtualMachineDiskInfo dumpElapsedTimeMs(Long dumpElapsedTimeMs) {
    this.dumpElapsedTimeMs = dumpElapsedTimeMs;
    return this;
  }

  /**
   * Get dumpElapsedTimeMs
   * @return dumpElapsedTimeMs
   **/
  @JsonProperty("DumpElapsedTimeMs")
  @Schema(description = "")
  public Long getDumpElapsedTimeMs() {
    return dumpElapsedTimeMs;
  }

  public void setDumpElapsedTimeMs(Long dumpElapsedTimeMs) {
    this.dumpElapsedTimeMs = dumpElapsedTimeMs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusVirtualMachineDiskInfo statusVirtualMachineDiskInfo = (StatusVirtualMachineDiskInfo) o;
    return Objects.equals(this.adapterType, statusVirtualMachineDiskInfo.adapterType) &&
        Objects.equals(this.busNumber, statusVirtualMachineDiskInfo.busNumber) &&
        Objects.equals(this.controllerDeviceKey, statusVirtualMachineDiskInfo.controllerDeviceKey) &&
        Objects.equals(this.unitNumber, statusVirtualMachineDiskInfo.unitNumber) &&
        Objects.equals(this.backupMode, statusVirtualMachineDiskInfo.backupMode) &&
        Objects.equals(this.capacity, statusVirtualMachineDiskInfo.capacity) &&
        Objects.equals(this.diskId, statusVirtualMachineDiskInfo.diskId) &&
        Objects.equals(this.dumpElapsedTimeMs, statusVirtualMachineDiskInfo.dumpElapsedTimeMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adapterType, busNumber, controllerDeviceKey, unitNumber, backupMode, capacity, diskId, dumpElapsedTimeMs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusVirtualMachineDiskInfo {\n");
    
    sb.append("    adapterType: ").append(toIndentedString(adapterType)).append("\n");
    sb.append("    busNumber: ").append(toIndentedString(busNumber)).append("\n");
    sb.append("    controllerDeviceKey: ").append(toIndentedString(controllerDeviceKey)).append("\n");
    sb.append("    unitNumber: ").append(toIndentedString(unitNumber)).append("\n");
    sb.append("    backupMode: ").append(toIndentedString(backupMode)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    diskId: ").append(toIndentedString(diskId)).append("\n");
    sb.append("    dumpElapsedTimeMs: ").append(toIndentedString(dumpElapsedTimeMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
