/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets StatusProfilePhases
 */
public enum StatusProfilePhases {
  NONE("NONE"),
    START("START"),
    START_ACCESS_ARCHIVE("START_ACCESS_ARCHIVE"),
    END_ACCESS_ARCHIVE("END_ACCESS_ARCHIVE"),
    START_RETRIEVE_GENERATIONS("START_RETRIEVE_GENERATIONS"),
    END_RETRIEVE_GENERATIONS("END_RETRIEVE_GENERATIONS"),
    START_RETRIEVE_GENERATIONS_INFO("START_RETRIEVE_GENERATIONS_INFO"),
    START_RETRIEVE_GENERATION_INFO("START_RETRIEVE_GENERATION_INFO"),
    END_RETRIEVE_GENERATION_INFO("END_RETRIEVE_GENERATION_INFO"),
    END_RETRIEVE_GENERATIONS_INFO("END_RETRIEVE_GENERATIONS_INFO"),
    END("END");

  private String value;

  StatusProfilePhases(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static StatusProfilePhases fromValue(String text) {
    for (StatusProfilePhases b : StatusProfilePhases.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
