/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.BackupMode;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * StatusDiskInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-08-31T19:06:45.540Z[GMT]")public class StatusDiskInfo   {
  @JsonProperty("BackupMode")
  private BackupMode backupMode = null;

  @JsonProperty("Capacity")
  private Long capacity = null;

  @JsonProperty("DiskId")
  private Integer diskId = null;

  @JsonProperty("DumpElapsedTimeMs")
  private Long dumpElapsedTimeMs = null;

  public StatusDiskInfo backupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
    return this;
  }

  /**
   * Get backupMode
   * @return backupMode
   **/
  @JsonProperty("BackupMode")
  @Schema(description = "")
  @Valid
  public BackupMode getBackupMode() {
    return backupMode;
  }

  public void setBackupMode(BackupMode backupMode) {
    this.backupMode = backupMode;
  }

  public StatusDiskInfo capacity(Long capacity) {
    this.capacity = capacity;
    return this;
  }

  /**
   * Get capacity
   * @return capacity
   **/
  @JsonProperty("Capacity")
  @Schema(description = "")
  public Long getCapacity() {
    return capacity;
  }

  public void setCapacity(Long capacity) {
    this.capacity = capacity;
  }

  public StatusDiskInfo diskId(Integer diskId) {
    this.diskId = diskId;
    return this;
  }

  /**
   * Get diskId
   * @return diskId
   **/
  @JsonProperty("DiskId")
  @Schema(description = "")
  public Integer getDiskId() {
    return diskId;
  }

  public void setDiskId(Integer diskId) {
    this.diskId = diskId;
  }

  public StatusDiskInfo dumpElapsedTimeMs(Long dumpElapsedTimeMs) {
    this.dumpElapsedTimeMs = dumpElapsedTimeMs;
    return this;
  }

  /**
   * Get dumpElapsedTimeMs
   * @return dumpElapsedTimeMs
   **/
  @JsonProperty("DumpElapsedTimeMs")
  @Schema(description = "")
  public Long getDumpElapsedTimeMs() {
    return dumpElapsedTimeMs;
  }

  public void setDumpElapsedTimeMs(Long dumpElapsedTimeMs) {
    this.dumpElapsedTimeMs = dumpElapsedTimeMs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusDiskInfo statusDiskInfo = (StatusDiskInfo) o;
    return Objects.equals(this.backupMode, statusDiskInfo.backupMode) &&
        Objects.equals(this.capacity, statusDiskInfo.capacity) &&
        Objects.equals(this.diskId, statusDiskInfo.diskId) &&
        Objects.equals(this.dumpElapsedTimeMs, statusDiskInfo.dumpElapsedTimeMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backupMode, capacity, diskId, dumpElapsedTimeMs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusDiskInfo {\n");
    
    sb.append("    backupMode: ").append(toIndentedString(backupMode)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    diskId: ").append(toIndentedString(diskId)).append("\n");
    sb.append("    dumpElapsedTimeMs: ").append(toIndentedString(dumpElapsedTimeMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
