/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.vmware.safekeeping.cxf.rest.model.FcoLocation;
import com.vmware.safekeeping.cxf.rest.model.ManagedEntityInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * VmLocation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-09-06T23:20:18.330Z[GMT]")public class VmLocation extends FcoLocation  {
  @JsonProperty("vAppMember")
  private Boolean vAppMember = null;

  @JsonProperty("datastorePath")
  private String datastorePath = null;

  @JsonProperty("vmxFullPath")
  private String vmxFullPath = null;

  @JsonProperty("vmFolderFullPath")
  private String vmFolderFullPath = null;

  @JsonProperty("vmxFileName")
  private String vmxFileName = null;

  @JsonProperty("vmFolderPath")
  private List<ManagedEntityInfo> vmFolderPath = null;

  @JsonProperty("resourcePoolPath")
  private List<ManagedEntityInfo> resourcePoolPath = null;

  @JsonProperty("resourcePoolInfo")
  private ManagedEntityInfo resourcePoolInfo = null;

  @JsonProperty("resourcePoolFullPath")
  private String resourcePoolFullPath = null;

  @JsonProperty("vmFolderInfo")
  private ManagedEntityInfo vmFolderInfo = null;

  @JsonProperty("datastoreInfo")
  private ManagedEntityInfo datastoreInfo = null;

  public VmLocation vAppMember(Boolean vAppMember) {
    this.vAppMember = vAppMember;
    return this;
  }

  /**
   * Get vAppMember
   * @return vAppMember
   **/
  @JsonProperty("vAppMember")
  @Schema(description = "")
  public Boolean isVAppMember() {
    return vAppMember;
  }

  public void setVAppMember(Boolean vAppMember) {
    this.vAppMember = vAppMember;
  }

  public VmLocation datastorePath(String datastorePath) {
    this.datastorePath = datastorePath;
    return this;
  }

  /**
   * Get datastorePath
   * @return datastorePath
   **/
  @JsonProperty("datastorePath")
  @Schema(description = "")
  public String getDatastorePath() {
    return datastorePath;
  }

  public void setDatastorePath(String datastorePath) {
    this.datastorePath = datastorePath;
  }

  public VmLocation vmxFullPath(String vmxFullPath) {
    this.vmxFullPath = vmxFullPath;
    return this;
  }

  /**
   * Get vmxFullPath
   * @return vmxFullPath
   **/
  @JsonProperty("vmxFullPath")
  @Schema(description = "")
  public String getVmxFullPath() {
    return vmxFullPath;
  }

  public void setVmxFullPath(String vmxFullPath) {
    this.vmxFullPath = vmxFullPath;
  }

  public VmLocation vmFolderFullPath(String vmFolderFullPath) {
    this.vmFolderFullPath = vmFolderFullPath;
    return this;
  }

  /**
   * Get vmFolderFullPath
   * @return vmFolderFullPath
   **/
  @JsonProperty("vmFolderFullPath")
  @Schema(description = "")
  public String getVmFolderFullPath() {
    return vmFolderFullPath;
  }

  public void setVmFolderFullPath(String vmFolderFullPath) {
    this.vmFolderFullPath = vmFolderFullPath;
  }

  public VmLocation vmxFileName(String vmxFileName) {
    this.vmxFileName = vmxFileName;
    return this;
  }

  /**
   * Get vmxFileName
   * @return vmxFileName
   **/
  @JsonProperty("vmxFileName")
  @Schema(description = "")
  public String getVmxFileName() {
    return vmxFileName;
  }

  public void setVmxFileName(String vmxFileName) {
    this.vmxFileName = vmxFileName;
  }

  public VmLocation vmFolderPath(List<ManagedEntityInfo> vmFolderPath) {
    this.vmFolderPath = vmFolderPath;
    return this;
  }

  public VmLocation addVmFolderPathItem(ManagedEntityInfo vmFolderPathItem) {
    if (this.vmFolderPath == null) {
      this.vmFolderPath = new ArrayList<ManagedEntityInfo>();
    }
    this.vmFolderPath.add(vmFolderPathItem);
    return this;
  }

  /**
   * Get vmFolderPath
   * @return vmFolderPath
   **/
  @JsonProperty("vmFolderPath")
  @Schema(description = "")
  @Valid
  public List<ManagedEntityInfo> getVmFolderPath() {
    return vmFolderPath;
  }

  public void setVmFolderPath(List<ManagedEntityInfo> vmFolderPath) {
    this.vmFolderPath = vmFolderPath;
  }

  public VmLocation resourcePoolPath(List<ManagedEntityInfo> resourcePoolPath) {
    this.resourcePoolPath = resourcePoolPath;
    return this;
  }

  public VmLocation addResourcePoolPathItem(ManagedEntityInfo resourcePoolPathItem) {
    if (this.resourcePoolPath == null) {
      this.resourcePoolPath = new ArrayList<ManagedEntityInfo>();
    }
    this.resourcePoolPath.add(resourcePoolPathItem);
    return this;
  }

  /**
   * Get resourcePoolPath
   * @return resourcePoolPath
   **/
  @JsonProperty("resourcePoolPath")
  @Schema(description = "")
  @Valid
  public List<ManagedEntityInfo> getResourcePoolPath() {
    return resourcePoolPath;
  }

  public void setResourcePoolPath(List<ManagedEntityInfo> resourcePoolPath) {
    this.resourcePoolPath = resourcePoolPath;
  }

  public VmLocation resourcePoolInfo(ManagedEntityInfo resourcePoolInfo) {
    this.resourcePoolInfo = resourcePoolInfo;
    return this;
  }

  /**
   * Get resourcePoolInfo
   * @return resourcePoolInfo
   **/
  @JsonProperty("resourcePoolInfo")
  @Schema(description = "")
  @Valid
  public ManagedEntityInfo getResourcePoolInfo() {
    return resourcePoolInfo;
  }

  public void setResourcePoolInfo(ManagedEntityInfo resourcePoolInfo) {
    this.resourcePoolInfo = resourcePoolInfo;
  }

  public VmLocation resourcePoolFullPath(String resourcePoolFullPath) {
    this.resourcePoolFullPath = resourcePoolFullPath;
    return this;
  }

  /**
   * Get resourcePoolFullPath
   * @return resourcePoolFullPath
   **/
  @JsonProperty("resourcePoolFullPath")
  @Schema(description = "")
  public String getResourcePoolFullPath() {
    return resourcePoolFullPath;
  }

  public void setResourcePoolFullPath(String resourcePoolFullPath) {
    this.resourcePoolFullPath = resourcePoolFullPath;
  }

  public VmLocation vmFolderInfo(ManagedEntityInfo vmFolderInfo) {
    this.vmFolderInfo = vmFolderInfo;
    return this;
  }

  /**
   * Get vmFolderInfo
   * @return vmFolderInfo
   **/
  @JsonProperty("vmFolderInfo")
  @Schema(description = "")
  @Valid
  public ManagedEntityInfo getVmFolderInfo() {
    return vmFolderInfo;
  }

  public void setVmFolderInfo(ManagedEntityInfo vmFolderInfo) {
    this.vmFolderInfo = vmFolderInfo;
  }

  public VmLocation datastoreInfo(ManagedEntityInfo datastoreInfo) {
    this.datastoreInfo = datastoreInfo;
    return this;
  }

  /**
   * Get datastoreInfo
   * @return datastoreInfo
   **/
  @JsonProperty("datastoreInfo")
  @Schema(description = "")
  @Valid
  public ManagedEntityInfo getDatastoreInfo() {
    return datastoreInfo;
  }

  public void setDatastoreInfo(ManagedEntityInfo datastoreInfo) {
    this.datastoreInfo = datastoreInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VmLocation vmLocation = (VmLocation) o;
    return Objects.equals(this.vAppMember, vmLocation.vAppMember) &&
        Objects.equals(this.datastorePath, vmLocation.datastorePath) &&
        Objects.equals(this.vmxFullPath, vmLocation.vmxFullPath) &&
        Objects.equals(this.vmFolderFullPath, vmLocation.vmFolderFullPath) &&
        Objects.equals(this.vmxFileName, vmLocation.vmxFileName) &&
        Objects.equals(this.vmFolderPath, vmLocation.vmFolderPath) &&
        Objects.equals(this.resourcePoolPath, vmLocation.resourcePoolPath) &&
        Objects.equals(this.resourcePoolInfo, vmLocation.resourcePoolInfo) &&
        Objects.equals(this.resourcePoolFullPath, vmLocation.resourcePoolFullPath) &&
        Objects.equals(this.vmFolderInfo, vmLocation.vmFolderInfo) &&
        Objects.equals(this.datastoreInfo, vmLocation.datastoreInfo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vAppMember, datastorePath, vmxFullPath, vmFolderFullPath, vmxFileName, vmFolderPath, resourcePoolPath, resourcePoolInfo, resourcePoolFullPath, vmFolderInfo, datastoreInfo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VmLocation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    vAppMember: ").append(toIndentedString(vAppMember)).append("\n");
    sb.append("    datastorePath: ").append(toIndentedString(datastorePath)).append("\n");
    sb.append("    vmxFullPath: ").append(toIndentedString(vmxFullPath)).append("\n");
    sb.append("    vmFolderFullPath: ").append(toIndentedString(vmFolderFullPath)).append("\n");
    sb.append("    vmxFileName: ").append(toIndentedString(vmxFileName)).append("\n");
    sb.append("    vmFolderPath: ").append(toIndentedString(vmFolderPath)).append("\n");
    sb.append("    resourcePoolPath: ").append(toIndentedString(resourcePoolPath)).append("\n");
    sb.append("    resourcePoolInfo: ").append(toIndentedString(resourcePoolInfo)).append("\n");
    sb.append("    resourcePoolFullPath: ").append(toIndentedString(resourcePoolFullPath)).append("\n");
    sb.append("    vmFolderInfo: ").append(toIndentedString(vmFolderInfo)).append("\n");
    sb.append("    datastoreInfo: ").append(toIndentedString(datastoreInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
