/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets WindowsQuiesceSpecVssBackupType
 */
public enum WindowsQuiesceSpecVssBackupType {
  COPY("VSS_BT_COPY"),
    DIFFERENTIAL("VSS_BT_DIFFERENTIAL"),
    FULL("VSS_BT_FULL"),
    INCREMENTAL("VSS_BT_INCREMENTAL"),
    LOG("VSS_BT_LOG"),
    OTHER("VSS_BT_OTHER"),
    UNDEFINED("VSS_BT_UNDEFINED");

  private String value;

  WindowsQuiesceSpecVssBackupType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static WindowsQuiesceSpecVssBackupType fromValue(String text) {
    for (WindowsQuiesceSpecVssBackupType b : WindowsQuiesceSpecVssBackupType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
