/*
 * Safekeeping Server
 * Safekeeping OpenAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.safekeeping.cxf.rest.model;

import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets WindowsQuiesceSpecVssBackupContext
 */
public enum WindowsQuiesceSpecVssBackupContext {
  AUTO("CTX_AUTO"),
    BACKUP("CTX_BACKUP"),
    FILE_SHARE_BACKUP("CTX_FILE_SHARE_BACKUP");

  private String value;

  WindowsQuiesceSpecVssBackupContext(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static WindowsQuiesceSpecVssBackupContext fromValue(String text) {
    for (WindowsQuiesceSpecVssBackupContext b : WindowsQuiesceSpecVssBackupContext.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
